<a href="https://colab.research.google.com/github/osergioribeirof/Python/blob/main/FED_Banco_Central_Americano_Dados_Economicos_dos_Estados_Unidos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <span style="color: gray;">**BIBLIOTECA**</span>

In [138]:
pip install --upgrade pandas_datareader

Requirement already satisfied: pandas_datareader in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (0.10.0)
Requirement already satisfied: lxml in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas_datareader) (6.0.1)
Requirement already satisfied: pandas>=0.23 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas_datareader) (2.3.2)
Requirement already satisfied: requests>=2.19.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas_datareader) (2.32.5)
Requirement already satisfied: numpy>=1.26.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas>=0.23->pandas_datareader) (2.3.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/sergioribeiromacbook/Library/Python/3.13/lib/python/site-packages (from pandas>=0.23->pandas_datareader) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas>=0.23->pandas_datareader) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas>=0.23->pandas_datareader) (2025.2)
Requirement already satisfied: six>=1.5 in /Users/sergioribeiromacbook/Library/Python/3.13/lib/python/site-packages (from python-dateutil>=2.8.2->pandas>=0.23->pandas_datareader) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from requests>=2.19.0->pandas_datareader) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from requests>=2.19.0->pandas_datareader) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from requests>=2.19.0->pandas_datareader) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from requests>=2.19.0->pandas_datareader) (2025.8.3)
Note: you may need to restart the kernel to use updated packages.

In [139]:
pip install pandas_datareader plotly

Requirement already satisfied: pandas_datareader in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (0.10.0)
Requirement already satisfied: plotly in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (6.3.0)
Requirement already satisfied: lxml in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas_datareader) (6.0.1)
Requirement already satisfied: pandas>=0.23 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas_datareader) (2.3.2)
Requirement already satisfied: requests>=2.19.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas_datareader) (2.32.5)
Requirement already satisfied: narwhals>=1.15.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from plotly) (2.5.0)
Requirement already satisfied: packaging in /Users/sergioribeiromacbook/Library/Python/3.13/lib/python/site-packages (from plotly) (25.0)
Requirement already satisfied: numpy>=1.26.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas>=0.23->pandas_datareader) (2.3.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/sergioribeiromacbook/Library/Python/3.13/lib/python/site-packages (from pandas>=0.23->pandas_datareader) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas>=0.23->pandas_datareader) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas>=0.23->pandas_datareader) (2025.2)
Requirement already satisfied: six>=1.5 in /Users/sergioribeiromacbook/Library/Python/3.13/lib/python/site-packages (from python-dateutil>=2.8.2->pandas>=0.23->pandas_datareader) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from requests>=2.19.0->pandas_datareader) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from requests>=2.19.0->pandas_datareader) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from requests>=2.19.0->pandas_datareader) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from requests>=2.19.0->pandas_datareader) (2025.8.3)
Note: you may need to restart the kernel to use updated packages.

In [140]:
pip install pandas_datareader

Requirement already satisfied: pandas_datareader in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (0.10.0)
Requirement already satisfied: lxml in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas_datareader) (6.0.1)
Requirement already satisfied: pandas>=0.23 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas_datareader) (2.3.2)
Requirement already satisfied: requests>=2.19.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas_datareader) (2.32.5)
Requirement already satisfied: numpy>=1.26.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas>=0.23->pandas_datareader) (2.3.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/sergioribeiromacbook/Library/Python/3.13/lib/python/site-packages (from pandas>=0.23->pandas_datareader) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas>=0.23->pandas_datareader) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas>=0.23->pandas_datareader) (2025.2)
Requirement already satisfied: six>=1.5 in /Users/sergioribeiromacbook/Library/Python/3.13/lib/python/site-packages (from python-dateutil>=2.8.2->pandas>=0.23->pandas_datareader) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from requests>=2.19.0->pandas_datareader) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from requests>=2.19.0->pandas_datareader) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from requests>=2.19.0->pandas_datareader) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from requests>=2.19.0->pandas_datareader) (2025.8.3)
Note: you may need to restart the kernel to use updated packages.

In [ ]:
pip install selenium

In [141]:
import pandas as pd
import matplotlib.cbook as cbook
import plotly.express as px
import datetime
import matplotlib.pyplot as plt
import numpy as np
import plotly.graph_objects as go

In [142]:
start = datetime.datetime(2015, 1, 1)
#end = datetime.datetime(2025, 12, 1)

# <span style="color: gray;"> **CÓDIGO INDICADORES**</span>

### Taxa de Desemprego (UnemPloyment Rate )

In [143]:
Unrate = web.DataReader('UNRATE', 'fred', start)

In [144]:
Unrate

            UNRATE
DATE
2015-01-01     5.7
2015-02-01     5.5
2015-03-01     5.4
2015-04-01     5.4
2015-05-01     5.6
...            ...
2025-04-01     4.2
2025-05-01     4.2
2025-06-01     4.1
2025-07-01     4.2
2025-08-01     4.3

[128 rows x 1 columns]

### Initial Calims - US

In [145]:
PedidosIniciais = web.DataReader('ICSA', 'fred', start)

In [146]:
PedidosIniciais

              ICSA
DATE
2015-01-03  294000
2015-01-10  304000
2015-01-17  298000
2015-01-24  261000
2015-01-31  281000
...            ...
2025-08-09  224000
2025-08-16  234000
2025-08-23  229000
2025-08-30  236000
2025-09-06  263000

[558 rows x 1 columns]

### JOLTs e JOLTs MoM

JOLTs

In [147]:
Jolts = web.DataReader('JTSJOL', 'fred', start )

In [148]:
Jolts

            JTSJOL
DATE
2015-01-01    5344
2015-02-01    5466
2015-03-01    5210
2015-04-01    5598
2015-05-01    5563
...            ...
2025-03-01    7200
2025-04-01    7395
2025-05-01    7712
2025-06-01    7357
2025-07-01    7181

[127 rows x 1 columns]

### Payroll - Vagas de Emprego (All Employess, Total Nonfarm)

In [149]:
Payroll = web.DataReader('PAYEMS', 'fred', start )

In [150]:
Payroll

            PAYEMS
DATE
2015-01-01  140568
2015-02-01  140827
2015-03-01  140923
2015-04-01  141196
2015-05-01  141538
...            ...
2025-04-01  159433
2025-05-01  159452
2025-06-01  159439
2025-07-01  159518
2025-08-01  159540

[128 rows x 1 columns]

### Taxa de Desemprego

In [151]:
desemprego = web.DataReader('UNRATE', 'fred', start)

In [152]:
desemprego

            UNRATE
DATE
2015-01-01     5.7
2015-02-01     5.5
2015-03-01     5.4
2015-04-01     5.4
2015-05-01     5.6
...            ...
2025-04-01     4.2
2025-05-01     4.2
2025-06-01     4.1
2025-07-01     4.2
2025-08-01     4.3

[128 rows x 1 columns]

### Producer Price Index (PPI - US)

In [153]:
PPI = web.DataReader('PPIFIS', 'fred', start)

In [154]:
PPI

             PPIFIS
DATE
2015-01-01  110.100
2015-02-01  109.600
2015-03-01  109.800
2015-04-01  109.600
2015-05-01  110.000
...             ...
2025-04-01  147.686
2025-05-01  148.227
2025-06-01  148.303
2025-07-01  149.341
2025-08-01  149.160

[128 rows x 1 columns]

### PCE

In [155]:
PCE = web.DataReader('PCEPI', 'fred', start)

In [156]:
PCE

              PCEPI
DATE
2015-01-01   96.654
2015-02-01   96.825
2015-03-01   97.008
2015-04-01   97.094
2015-05-01   97.327
...             ...
2025-03-01  125.791
2025-04-01  125.977
2025-05-01  126.172
2025-06-01  126.533
2025-07-01  126.783

[127 rows x 1 columns]

### Core-PCE

In [157]:
COREPCE = web.DataReader('PCEPILFE', 'fred', start)

In [158]:
COREPCE

            PCEPILFE
DATE
2015-01-01    96.214
2015-02-01    96.324
2015-03-01    96.470
2015-04-01    96.648
2015-05-01    96.766
...              ...
2025-03-01   125.118
2025-04-01   125.329
2025-05-01   125.579
2025-06-01   125.909
2025-07-01   126.253

[127 rows x 1 columns]

### Balanço Patrimônial do Federal Reserve ###

In [179]:
BPFEDERALRESERVE = web.DataReader('WALCL', 'fred', start)

In [180]:
BPFEDERALRESERVE

              WALCL
DATE
2007-01-03   874626
2007-01-10   854819
2007-01-17   859363
2007-01-24   851755
2007-01-31   865730
...             ...
2025-08-13  6643615
2025-08-20  6618415
2025-08-27  6603384
2025-09-03  6602071
2025-09-10  6605962

[976 rows x 1 columns]

# <span style="color: gray;"> **INDICADORES**</span>

# <span style="color: gray;"> **Primeira Semana**</span>

### JOLTs ###

In [178]:
import plotly.express as px
import numpy as np

# Filtrar dados de 2024 até hoje
Jolts_filtered = Jolts[Jolts.index >= '2023-01-01']

# Calcular a média do período
media_periodo = Jolts_filtered['JTSJOL'].mean()

# Criar o gráfico de barras
fig = px.bar(Jolts_filtered, x=Jolts_filtered.index, y='JTSJOL')

# Adicionar os valores em cima de cada barra
fig.update_traces(
    text=Jolts_filtered['JTSJOL'],  # Os valores a serem mostrados
    textposition='outside',  # Posição do texto (em cima das barras)
    texttemplate='%{text}',  # Formato do texto
)

# Adicionar linha da média
fig.add_hline(
    y=media_periodo,
    line_dash="solid",
    line_color="orange",
    line_width=2,
    annotation_text=f"Média: {media_periodo:.1f}",
    annotation_position="top right"
)

# Opcional: personalizar o layout
fig.update_layout(
    title="JTSJOL por Mês",
    xaxis_title="Mês",
    yaxis_title="JTSJOL",
    showlegend=False
)

# Mostrar o gráfico
fig.show()

### Pedidos Iniciais - Initial Calims - US ###

In [171]:
import plotly.express as px
import numpy as np

# Filtrar dados de 2024 até hoje
PedidosIniciais_filtered = PedidosIniciais[PedidosIniciais.index >= '2025-01-01']

# Calcular a média do período
media_periodo = PedidosIniciais_filtered['ICSA'].mean()

# Criar o gráfico de barras
fig = px.bar(PedidosIniciais_filtered, x=PedidosIniciais_filtered.index, y='ICSA')

# Adicionar os valores em cima de cada barra
fig.update_traces(
    text=PedidosIniciais_filtered['ICSA'],  # Os valores a serem mostrados
    textposition='outside',  # Posição do texto (em cima das barras)
    texttemplate='%{text}',  # Formato do texto
)

# Adicionar linha da média
fig.add_hline(
    y=media_periodo,
    line_dash="solid",
    line_color="orange",
    line_width=2,
    annotation_text=f"Média: {media_periodo:.1f}",
    annotation_position="top right"
)

# Opcional: personalizar o layout
fig.update_layout(
    title="ICSA por Mês",
    xaxis_title="Mês",
    yaxis_title="ICSA",
    showlegend=False
)

# Mostrar o gráfico
fig.show()

### Balanço Patrimônial do Federal Reserve

In [184]:
px.line(BPFEDERALRESERVE, x=BPFEDERALRESERVE.index, y='WALCL')

### Payroll (Investing.com)

In [46]:
import pandas_datareader.data as web
import datetime
import plotly.express as px  # Import plotly.express for line chart

# Definir a data de início
start = datetime.datetime(2022, 1, 1)

# Coletar dados do Payroll (PAYEMS)
Payroll = web.DataReader('PAYEMS', 'fred', start)

# Calcular a diferença entre o valor atual e o valor do mês passado
Payroll['Diff'] = Payroll['PAYEMS'].diff()

# Multiplicar a diferença por 1000 para obter o novo valor do Payroll
Payroll['PAYEMS'] = Payroll['Diff'] * 1000

# Remover a primeira linha que contém um valor NaN na coluna 'Diff'
Payroll = Payroll.dropna()

# Criar o gráfico de linha com Plotly Express
fig = px.bar(Payroll, x=Payroll.index, y='PAYEMS', title='Payroll', text_auto='.2s')


# Formatar eixo x para mostrar ano e mês
fig.update_xaxes(
    tickformat="%Y-%m",  # Formato para ano e mês (YYYY-MM)
    dtick="M1",          # Intervalo de ticks mensal
    title_text="Data"     # Título do eixo x (opcional)
)

# Configurar layout do gráfico
fig.update_layout(yaxis_title='Valor')
# Change 'clipon' to 'cliponaxis'
fig.update_traces(textfont_size=12, textangle=0, textposition="outside", cliponaxis=False)

# Exibir o gráfico
fig.show()

### Taxa de Desemprego ###

In [174]:
import plotly.express as px
import numpy as np

# Filtrar dados de 2024 até hoje
desemprego_filtered = desemprego[desemprego.index >= '2022-01-01']

# Calcular a média do período
media_periodo = desemprego_filtered['UNRATE'].mean()

# Criar o gráfico de barras
fig = px.bar(desemprego_filtered, x=desemprego_filtered.index, y='UNRATE')

# Adicionar os valores em cima de cada barra
fig.update_traces(
    text=desemprego_filtered['UNRATE'],  # Os valores a serem mostrados
    textposition='outside',  # Posição do texto (em cima das barras)
    texttemplate='%{text}',  # Formato do texto
)

# Adicionar linha da média
fig.add_hline(
    y=media_periodo,
    line_dash="solid",
    line_color="orange",
    line_width=2,
    annotation_text=f"Média: {media_periodo:.1f}",
    annotation_position="top right"
)

# Opcional: personalizar o layout
fig.update_layout(
    title="UNRATE por Mês",
    xaxis_title="Mês",
    yaxis_title="UNRATE (%)",
    showlegend=False
)

# Mostrar o gráfico
fig.show()

### Unemployment Rate e U.Rate 12m

In [177]:
import pandas_datareader.data as web
import datetime
import plotly.graph_objects as go

start = datetime.datetime(2007, 1, 1)
Unrate = web.DataReader('UNRATE', 'fred', start)

Unrate['12m_Avg'] = Unrate['UNRATE'].rolling(window=12).mean()

fig = go.Figure()
fig.add_trace(go.Scatter(x=Unrate.index, y=Unrate['UNRATE'], name='Unrate', line=dict(color='blue')))
fig.add_trace(go.Scatter(x=Unrate.index, y=Unrate['12m_Avg'], name='12m Avg', line=dict(color='darkorange')))
fig.update_layout(title='Unrate e Média de 12 Meses',
                  yaxis_title='Taxa de Desemprego', xaxis_title='Data')
fig.show()

# <span style="color: gray;"> **Segunda Semana**</span>

### Producer Price Index (IPP- US)

In [63]:
px.line(PPI, x=PPI.index, y='PPIFIS')

### Core Producer Price Index (Core IPP - US)

In [57]:
COREPPI = web.DataReader('WPSFD49116', 'fred', start)

In [58]:
COREPPI

            WPSFD49116
DATE
2022-01-01     121.392
2022-02-01     121.684
2022-03-01     122.779
2022-04-01     123.381
2022-05-01     124.002
2022-06-01     124.317
2022-07-01     124.571
2022-08-01     124.912
2022-09-01     125.280
2022-10-01     125.493
2022-11-01     125.961
2022-12-01     126.210
2023-01-01     126.774
2023-02-01     127.185
2023-03-01     127.335
2023-04-01     127.545
2023-05-01     127.570
2023-06-01     127.853
2023-07-01     128.145
2023-08-01     128.490
2023-09-01     128.894
2023-10-01     128.994
2023-11-01     129.138
2023-12-01     129.663
2024-01-01     130.242
2024-02-01     130.683
2024-03-01     131.003
2024-04-01     131.636
2024-05-01     131.905
2024-06-01     132.143
2024-07-01     132.655
2024-08-01     132.981
2024-09-01     133.257
2024-10-01     133.614
2024-11-01     133.767
2024-12-01     134.301
2025-01-01     134.837
2025-02-01     135.347
2025-03-01     135.519
2025-04-01     135.251
2025-05-01     135.425
2025-06-01     135.494
2025-07-01     136.254
2025-08-01     136.702

In [59]:
px.line(COREPPI, x=COREPPI.index, y='WPSFD49116')

### IPP E Core IPP (Annual)

In [106]:
import pandas_datareader.data as web
import datetime
import plotly.express as px

# ... (código anterior para coletar e preparar dados) ...

# Cria o gráfico com cores especificadas
fig = px.line(yoy_data,
              x=yoy_data.index,
              y=['PPI', 'Core PPI'],
              title='Annual PPI e Annual CorePPI',
              color_discrete_map={'PPI': 'blue', 'Core PPI': 'darkorange'})

# Remove a linha pontilhada em 2.0 (comente ou remova esta parte)
# fig.add_shape(type='line',
#               x0=yoy_data.index.min(),
#               y0=2,
#               x1=yoy_data.index.max(),
#               y1=2,
#               line=dict(color='black', dash='dot'))


# Adiciona uma linha sólida em 0%
fig.add_shape(type='line',
              x0=yoy_data.index.min(),
              y0=0,
              x1=yoy_data.index.max(),
              y1=0,
              line=dict(color='black'))

fig.update_layout(yaxis_title='Variação Percentual Anual (%)',
                  xaxis_title='Data')
fig.show()

ValueError: All arguments should have the same length. The length of argument `y` is 2, whereas the length of previously-processed arguments ['DATE'] is 308

### IPP E Core IPP (Variação Mensal)

In [107]:
#PPI and Core PPI (Monthly Percentage Change) Bar Chart
import pandas_datareader.data as web
import datetime
import plotly.express as px
import pandas as pd

# Definir a data de início e fim
start = datetime.datetime(2023, 1, 1)
end = datetime.datetime(2025, 12, 31)

# Coletar dados do PPI e Core PPI dentro do período especificado
ppi = web.DataReader('PPIFIS', 'fred', start, end)
coreppi = web.DataReader('WPSFD49116', 'fred', start, end)

# Calcular a variação percentual
ppi_percentual = ppi.pct_change()*100
coreppi_percentual = coreppi.pct_change()*100

# Juntar os dados em um único DataFrame para o gráfico
dados_grafico = pd.concat([ppi_percentual.rename(columns={'PPIFIS': 'PPI'}),
                           coreppi_percentual.rename(columns={'WPSFD49116': 'CorePPI'})], axis=1)

# Arredondar os valores para duas casas decimais
dados_grafico['PPI'] = dados_grafico['PPI'].round(2)
dados_grafico['CorePPI'] = dados_grafico['CorePPI'].round(2)

# Criar o gráfico com Plotly Express
fig = px.bar(dados_grafico,
             x=dados_grafico.index,
             y=['PPI', 'CorePPI'],
             barmode='group',
             labels={'value': 'Variação Percentual (%)', 'variable': 'Índice'},
             text_auto=True,  # Exibir os valores arredondados
             color_discrete_map={'PPI': 'blue', 'CorePPI': 'darkorange'},
             title="PPI e CorePPI (Variação Mensal)")  # Adiciona o título

# Formatar o eixo x para mostrar ano e mês
fig.update_xaxes(
    tickformat="%Y-%m",  # Formato para ano e mês (YYYY-MM)
    dtick="M1",          # Intervalo de ticks mensal
    title_text="Data (Ano-Mês)"  # Título do eixo x
)

# Ajustar a posição e o tamanho da fonte dos números acima das barras
fig.update_traces(textposition='outside', textfont_size=25)

# Personalizar o formato do texto para incluir o símbolo de porcentagem
fig.update_traces(texttemplate='%{y:.2f}%')

# Exibir o gráfico
fig.show()

### IPC

In [97]:
# Multiple series:
cpi = web.DataReader('CPIAUCSL', 'fred', start)

In [ ]:
cpi

            CPIAUCSL
DATE
2020-01-01   259.127
2020-02-01   259.250
2020-03-01   258.076
2020-04-01   256.032
2020-05-01   255.802
...              ...
2024-09-01   314.851
2024-10-01   315.564
2024-11-01   316.449
2024-12-01   317.603
2025-01-01   319.086

[61 rows x 1 columns]

In [ ]:
px.line(cpi, x=cpi.index, y='CPIAUCSL')

### Core IPC (Core Consumer Price Index - US)

In [98]:
CoreCPI = web.DataReader('CPILFESL', 'fred', start)

In [99]:
CoreCPI

            CPILFESL
DATE
2015-01-01   239.811
2015-02-01   240.172
2015-03-01   240.755
2015-04-01   241.346
2015-05-01   241.688
...              ...
2025-04-01   326.430
2025-05-01   326.854
2025-06-01   327.600
2025-07-01   328.656
2025-08-01   329.793

[128 rows x 1 columns]

In [100]:
px.line(CoreCPI, x=CoreCPI.index, y='CPILFESL')

### IPC and Core IPC (YoY Comparison)

In [105]:
import pandas_datareader.data as web
import datetime
import plotly.express as px

start = datetime.datetime(2000, 1, 1)
end = datetime.datetime.now()

cpi = web.DataReader('CPIAUCSL', 'fred', start, end)
core_cpi = web.DataReader('CPILFESL', 'fred', start, end)

# Calculate YoY percentage change
cpi['YoY_Change'] = cpi['CPIAUCSL'].pct_change(periods=12) * 100
core_cpi['YoY_Change'] = core_cpi['CPILFESL'].pct_change(periods=12) * 100

# Combine data for plotting
yoy_data = cpi[['YoY_Change']].rename(columns={'YoY_Change': 'CPI'})
yoy_data['Core CPI'] = core_cpi['YoY_Change']

# Create the chart with specified colors
fig = px.line(yoy_data,
              x=yoy_data.index,
              y=['CPI', 'Core CPI'],
              title='CPI and Core CPI YoY Comparison',
              color_discrete_map={'CPI': 'blue', 'Core CPI': 'darkorange'})

# Add a dotted line at 2%
fig.add_shape(type='line',
              x0=yoy_data.index.min(),
              y0=2,
              x1=yoy_data.index.max(),
              y1=2,
              line=dict(color='black', dash='dot'))

# Add a solid line at 0%
fig.add_shape(type='line',
              x0=yoy_data.index.min(),
              y0=0,
              x1=yoy_data.index.max(),
              y1=0,
              line=dict(color='black'))

fig.update_layout(yaxis_title='YoY Percentage Change (%)',
                  xaxis_title='Date')
fig.show()

### IPC E Core IPC (Variação Mensal)

In [103]:
#CPI E CORE CPI (VARIAÇÃO MENSAL)
import pandas_datareader.data as web
import datetime
import plotly.express as px
import pandas as pd

# Definir a data de início e fim
start = datetime.datetime(2023, 1, 1)
end = datetime.datetime(2025, 12, 31)

# Coletar dados do CPI e Core CPI dentro do período especificado
cpi = web.DataReader('CPIAUCSL', 'fred', start, end)
corecpi = web.DataReader('CPILFESL', 'fred', start, end)  # Usando CPILFESL para Core CPI

# Calcular a variação percentual
cpi_percentual = cpi.pct_change()*100
corecpi_percentual = corecpi.pct_change()*100

# Juntar os dados em um único DataFrame para o gráfico
dados_grafico = pd.concat([cpi_percentual.rename(columns={'CPIAUCSL': 'CPI'}),
                           corecpi_percentual.rename(columns={'CPILFESL': 'CoreCPI'})], axis=1)

# Arredondar os valores para duas casas decimais
dados_grafico['CPI'] = dados_grafico['CPI'].round(2)
dados_grafico['CoreCPI'] = dados_grafico['CoreCPI'].round(2)

# Criar o gráfico com Plotly Express
fig = px.bar(dados_grafico,
             x=dados_grafico.index,
             y=['CPI', 'CoreCPI'],
             barmode='group',
             labels={'value': 'Variação Percentual (%)', 'variable': 'Índice'},
             text_auto=True,  # Exibir os valores arredondados
             color_discrete_map={'CPI': 'blue', 'CoreCPI': 'darkorange'},
             title="CPI e Core CPI (Variação Mensal)")  # Adiciona o título

# Formatar o eixo x para mostrar ano e mês
fig.update_xaxes(
    tickformat="%Y-%m",  # Formato para ano e mês (YYYY-MM)
    dtick="M1",          # Intervalo de ticks mensal
    title_text="Data (Ano-Mês)"  # Título do eixo x
)

# Ajustar a posição e o tamanho da fonte dos números acima das barras
fig.update_traces(textposition='outside', textfont_size=25)

# Personalizar o formato do texto para incluir o símbolo de porcentagem
fig.update_traces(texttemplate='%{y:.2f}%')

# Exibir o gráfico
fig.show()

### Core IPC (3M E 6M Annualized)

In [ ]:
import pandas_datareader.data as web
import datetime
import plotly.express as px

# ... (código anterior para coletar e preparar dados) ...

# Cria o gráfico com cores especificadas
fig = px.line(core_cpi,
              x=core_cpi.index,
              y=['3-Month_Annualized', '6-Month_Annualized'],
              title='Core CPI Anualizado em 3 e 6 Meses',
              color_discrete_map={'3-Month_Annualized': 'blue', '6-Month_Annualized': 'darkorange'})

# Adiciona uma linha sólida em 0%
fig.add_shape(type='line',
              x0=core_cpi.index.min(),
              y0=0,
              x1=core_cpi.index.max(),
              y1=0,
              line=dict(color='black'))

# Adiciona uma linha pontilhada preta em 0.02
fig.add_shape(type='line',
              x0=core_cpi.index.min(),
              y0=0.02,
              x1=core_cpi.index.max(),
              y1=0.02,
              line=dict(color='black', dash='dot'))  # dash='dot' cria a linha pontilhada


fig.update_layout(yaxis_title='Variação Percentual Anualizada (%)',
                  xaxis_title='Data',
                 legend_title_text='')  # Remove o título da legenda

fig.show()

# <span style="color: gray;"> **Terceira Semana**</span>

# <span style="color: gray;"> **Quarta Semana**</span>

### PCE ###

In [81]:
px.line(PCE, x=PCE.index, y='PCEPI')

### CORE PCE

In [82]:
px.line(COREPCE, x=COREPCE.index, y='PCEPILFE')

### PCE E Core PCE (Variação Mensal)

In [95]:
#PCE E CORE PCE (VARIAÇÃO MENSAL)
import pandas_datareader.data as web
import datetime
import plotly.express as px
import pandas as pd

# Definir a data de início e fim
start = datetime.datetime(2023, 1, 1)
end = datetime.datetime(2025, 12, 31)

# Coletar dados do PCE e Core PCE dentro do período especificado
pce = web.DataReader('PCEPI', 'fred', start, end)
corepce = web.DataReader('PCEPILFE', 'fred', start, end)

# Calcular a variação percentual
pce_percentual = pce.pct_change()*100
corepce_percentual = corepce.pct_change()*100

# Juntar os dados em um único DataFrame para o gráfico
dados_grafico = pd.concat([pce_percentual.rename(columns={'PCEPI': 'PCE'}),
                           corepce_percentual.rename(columns={'PCEPILFE': 'CorePCE'})], axis=1)

# Arredondar os valores para duas casas decimais
dados_grafico['PCE'] = dados_grafico['PCE'].round(2)
dados_grafico['CorePCE'] = dados_grafico['CorePCE'].round(2)

# Criar o gráfico com Plotly Express
fig = px.bar(dados_grafico,
             x=dados_grafico.index,
             y=['PCE', 'CorePCE'],
             barmode='group',
             labels={'value': 'Variação Percentual (%)', 'variable': 'Índice'},
             text_auto=True,  # Exibir os valores arredondados
             color_discrete_map={'PCE': 'blue', 'CorePCE': 'darkorange'},  # Define as cores
             title="PCE e Core PCE (Variação Mensal)")  # Adiciona o título

# Formatar o eixo x para mostrar ano e mês
fig.update_xaxes(
    tickformat="%Y-%m",  # Formato para ano e mês (YYYY-MM)
    dtick="M1",          # Intervalo de ticks mensal
    title_text="Data (Ano-Mês)"  # Título do eixo x
)

# Ajustar a posição e o tamanho da fonte dos números acima das barras
fig.update_traces(textposition='outside', textfont_size=25)

# Personalizar o formato do texto para incluir o símbolo de porcentagem
fig.update_traces(texttemplate='%{y:.2f}%')

# Exibir o gráfico
fig.show()

### PCE E Core PCE (YoY Comparison)

In [94]:
import pandas_datareader.data as web
import datetime
import plotly.express as px

start = datetime.datetime(2000, 1, 1)
end = datetime.datetime.now()

pce = web.DataReader('PCEPI', 'fred', start, end)
core_pce = web.DataReader('PCEPILFE', 'fred', start, end)

# Calculate YoY percentage change
pce['YoY_Change'] = pce['PCEPI'].pct_change(periods=12) * 100
core_pce['YoY_Change'] = core_pce['PCEPILFE'].pct_change(periods=12) * 100

# Combine data for plotting
yoy_data = pce[['YoY_Change']].rename(columns={'YoY_Change': 'PCE'})
yoy_data['Core PCE'] = core_pce['YoY_Change']

# Create the chart with specified colors
fig = px.line(yoy_data,
              x=yoy_data.index,
              y=['PCE', 'Core PCE'],
              title='PCE and Core PCE YoY Comparison',
              color_discrete_map={'PCE': 'blue', 'Core PCE': 'darkorange'})  # Add color mapping

# Add a dotted line at 2%
fig.add_shape(type='line',
              x0=yoy_data.index.min(),
              y0=2,
              x1=yoy_data.index.max(),
              y1=2,
              line=dict(color='black', dash='dot'))

# Add a solid line at 0%
fig.add_shape(type='line',
              x0=yoy_data.index.min(),
              y0=0,
              x1=yoy_data.index.max(),
              y1=0,
              line=dict(color='black'))  # Default line is solid

fig.update_layout(yaxis_title='YoY Percentage Change (%)',
                  xaxis_title='Date')
fig.show()

### Core PCE (3M E 6M Annualized)

In [96]:
import pandas_datareader.data as web
import datetime
import plotly.express as px

start = datetime.datetime(2015, 1, 1)
end = datetime.datetime.now()

core_pce = web.DataReader('PCEPILFE', 'fred', start, end)

# Calcula a variação percentual
core_pce['3-Month_Change'] = core_pce['PCEPILFE'].pct_change(periods=3)
core_pce['6-Month_Change'] = core_pce['PCEPILFE'].pct_change(periods=6)

# Anualiza a variação percentual
core_pce['3-Month_Annualized'] = (1 + core_pce['3-Month_Change']) ** (12 / 3) - 1
core_pce['6-Month_Annualized'] = (1 + core_pce['6-Month_Change']) ** (12 / 6) - 1


# Cria o gráfico com cores especificadas
fig = px.line(core_pce,
              x=core_pce.index,
              y=['3-Month_Annualized', '6-Month_Annualized'],
              title='Core PCE Anualizado em 3 e 6 Meses',
              color_discrete_map={'3-Month_Annualized': 'blue', '6-Month_Annualized': 'darkorange'})

# Adiciona uma linha sólida em 0%
fig.add_shape(type='line',
              x0=core_pce.index.min(),
              y0=0,
              x1=core_pce.index.max(),
              y1=0,
              line=dict(color='black'))

# Adiciona uma linha pontilhada preta em 0.02
fig.add_shape(type='line',
              x0=core_pce.index.min(),
              y0=0.02,
              x1=core_pce.index.max(),
              y1=0.02,
              line=dict(color='black', dash='dot'))  # dash='dot' cria a linha pontilhada


fig.update_layout(yaxis_title='Variação Percentual Anualizada (%)',
                  xaxis_title='Data',
                 legend_title_text='')  # Remove o título da legenda

fig.show()