<a href="https://colab.research.google.com/github/osergioribeirof/Python/blob/main/FED_Banco_Central_Americano_Dados_Economicos_dos_Estados_Unidos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### FED Banco Central Americano - Dados Economicos dos Estados Unidos

# <span style="color: gray;">**BIBLIOTECA**</span>

In [10]:
pip install --upgrade pandas_datareader

Requirement already satisfied: pandas_datareader in /usr/local/lib/python3.12/dist-packages (0.10.0)
Requirement already satisfied: lxml in /usr/local/lib/python3.12/dist-packages (from pandas_datareader) (5.4.0)
Requirement already satisfied: pandas>=0.23 in /usr/local/lib/python3.12/dist-packages (from pandas_datareader) (2.2.2)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.12/dist-packages (from pandas_datareader) (2.32.4)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.23->pandas_datareader) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.23->pandas_datareader) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.23->pandas_datareader) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.23->pandas_datareader) (2025.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->pandas_datareader) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->pandas_datareader) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->pandas_datareader) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->pandas_datareader) (2025.8.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=0.23->pandas_datareader) (1.17.0)

In [11]:
pip install pandas_datareader plotly

Requirement already satisfied: pandas_datareader in /usr/local/lib/python3.12/dist-packages (0.10.0)
Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (5.24.1)
Requirement already satisfied: lxml in /usr/local/lib/python3.12/dist-packages (from pandas_datareader) (5.4.0)
Requirement already satisfied: pandas>=0.23 in /usr/local/lib/python3.12/dist-packages (from pandas_datareader) (2.2.2)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.12/dist-packages (from pandas_datareader) (2.32.4)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly) (8.5.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from plotly) (25.0)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.23->pandas_datareader) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.23->pandas_datareader) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.23->pandas_datareader) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.23->pandas_datareader) (2025.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->pandas_datareader) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->pandas_datareader) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->pandas_datareader) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->pandas_datareader) (2025.8.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=0.23->pandas_datareader) (1.17.0)

In [12]:
pip install pandas_datareader

Requirement already satisfied: pandas_datareader in /usr/local/lib/python3.12/dist-packages (0.10.0)
Requirement already satisfied: lxml in /usr/local/lib/python3.12/dist-packages (from pandas_datareader) (5.4.0)
Requirement already satisfied: pandas>=0.23 in /usr/local/lib/python3.12/dist-packages (from pandas_datareader) (2.2.2)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.12/dist-packages (from pandas_datareader) (2.32.4)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.23->pandas_datareader) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.23->pandas_datareader) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.23->pandas_datareader) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.23->pandas_datareader) (2025.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->pandas_datareader) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->pandas_datareader) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->pandas_datareader) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->pandas_datareader) (2025.8.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=0.23->pandas_datareader) (1.17.0)

In [13]:
import pandas as pd
import matplotlib.cbook as cbook
import plotly.express as px
import datetime
import matplotlib.pyplot as plt
import numpy as np
import plotly.graph_objects as go

In [14]:
start = datetime.datetime(2015, 1, 1)
#end = datetime.datetime(2025, 12, 1)

# <span style="color: gray;">**HOUSING** **MARKET**</span>  🏠

### 30y Mortgage Rate (Average)

In [16]:
import pandas as pd
import datetime
import plotly.express as px
from pandas_datareader import data as web



start = datetime.datetime(2015, 1, 1)
MortgageRate = web.DataReader('MORTGAGE30US', 'fred', start)
px.line(MortgageRate, x=MortgageRate.index, y='MORTGAGE30US', title='30y Mortgage Rate (Average)')  # Plota o gráfico

In [17]:
MortgageRate

            MORTGAGE30US
DATE
2015-01-08          3.73
2015-01-15          3.66
2015-01-22          3.63
2015-01-29          3.66
2015-02-05          3.59
...                  ...
2025-08-14          6.58
2025-08-21          6.58
2025-08-28          6.56
2025-09-04          6.50
2025-09-11          6.35

[558 rows x 1 columns]

### Houses Under Construction

In [ ]:
import pandas_datareader.data as web
import datetime
import plotly.express as px

start = datetime.datetime(2000, 1, 1)
HOUSECONSTRUCTION = web.DataReader('UNDCONTSA', 'fred', start)
px.line(HOUSECONSTRUCTION, x=HOUSECONSTRUCTION.index, y='UNDCONTSA', title='Houses Under Construction')  # Plota o gráfico

### Housing Starts

In [ ]:
HOUSESTARTS = web.DataReader('HOUST', 'fred', start)

In [ ]:
HOUSESTARTS

            HOUST
DATE
2000-01-01   1636
2000-02-01   1737
2000-03-01   1604
2000-04-01   1626
2000-05-01   1575
...           ...
2024-09-01   1355
2024-10-01   1344
2024-11-01   1305
2024-12-01   1515
2025-01-01   1366

[301 rows x 1 columns]

In [ ]:
px.line(HOUSESTARTS, x=HOUSESTARTS.index, y='HOUST')

### Building Permits

In [ ]:
BuildingPermits = web.DataReader('PERMIT', 'fred', start)

In [ ]:
BuildingPermits

            PERMIT
DATE
2020-01-01    1507
2020-02-01    1442
2020-03-01    1358
2020-04-01    1066
2020-05-01    1260
2020-06-01    1338
2020-07-01    1546
2020-08-01    1529
2020-09-01    1624
2020-10-01    1613
2020-11-01    1714
2020-12-01    1744
2021-01-01    1883
2021-02-01    1715
2021-03-01    1732
2021-04-01    1738
2021-05-01    1681
2021-06-01    1657
2021-07-01    1652
2021-08-01    1770
2021-09-01    1625
2021-10-01    1719
2021-11-01    1766
2021-12-01    1913
2022-01-01    1915
2022-02-01    1860
2022-03-01    1879
2022-04-01    1835
2022-05-01    1712
2022-06-01    1745
2022-07-01    1719
2022-08-01    1542
2022-09-01    1613
2022-10-01    1560
2022-11-01    1402
2022-12-01    1400
2023-01-01    1443
2023-02-01    1620
2023-03-01    1493
2023-04-01    1470
2023-05-01    1532
2023-06-01    1493
2023-07-01    1501
2023-08-01    1578
2023-09-01    1515
2023-10-01    1534
2023-11-01    1508
2023-12-01    1530
2024-01-01    1508
2024-02-01    1563
2024-03-01    1485
2024-04-01    1440
2024-05-01    1399
2024-06-01    1454
2024-07-01    1406
2024-08-01    1470
2024-09-01    1425
2024-10-01    1419
2024-11-01    1493
2024-12-01    1482

In [ ]:
px.line(BuildingPermits, x=BuildingPermits.index, y='PERMIT')

### Housing Starts e Building Permits

In [ ]:
import pandas_datareader.data as web
import datetime
import plotly.graph_objects as go

start = datetime.datetime(2000, 1, 1) # Make sure start is defined

# Fetch the data for HOUSESTARTS
HOUSESTARTS = web.DataReader('HOUST', 'fred', start)

# Fetch the data for Building Permits (Assuming you've already fetched it)
BuildingPermits = web.DataReader('PERMIT', 'fred', start)

# Now you can create your figure
fig = go.Figure()

fig.add_trace(go.Scatter(x=HOUSESTARTS.index, y=HOUSESTARTS['HOUST'],
                         mode='lines',
                         name='Housing Starts',
                         line=dict(color='darkorange')))

fig.add_trace(go.Scatter(x=BuildingPermits.index, y=BuildingPermits['PERMIT'],
                         mode='lines',
                         name='Building Permits',
                         line=dict(color='blue')))

fig.update_layout(title='Housing Starts e Building Permits',
                  xaxis_title='Data',
                  yaxis_title='Valor')

fig.show()

### Total Construction Spending

In [ ]:
TOTALCONSTRUCT = web.DataReader('TTLCONS', 'fred', start)

In [ ]:
TOTALCONSTRUCT

            TTLCONS
DATE
2020-01-01  1490544
2020-02-01  1498345
2020-03-01  1505604
2020-04-01  1459249
2020-05-01  1452280
2020-06-01  1461261
2020-07-01  1473560
2020-08-01  1491409
2020-09-01  1510420
2020-10-01  1534371
2020-11-01  1551966
2020-12-01  1573791
2021-01-01  1601386
2021-02-01  1580186
2021-03-01  1610868
2021-04-01  1617204
2021-05-01  1630067
2021-06-01  1639714
2021-07-01  1661458
2021-08-01  1666755
2021-09-01  1669575
2021-10-01  1685471
2021-11-01  1728158
2021-12-01  1757320
2022-01-01  1810368
2022-02-01  1852805
2022-03-01  1878681
2022-04-01  1918254
2022-05-01  1930664
2022-06-01  1918140
2022-07-01  1925909
2022-08-01  1915377
2022-09-01  1914299
2022-10-01  1907841
2022-11-01  1913413
2022-12-01  1922389
2023-01-01  1932302
2023-02-01  1944950
2023-03-01  1964793
2023-04-01  1990292
2023-05-01  2011831
2023-06-01  2023013
2023-07-01  2027412
2023-08-01  2047414
2023-09-01  2055216
2023-10-01  2071136
2023-11-01  2090690
2023-12-01  2101292
2024-01-01  2122229
2024-02-01  2133750
2024-03-01  2135771
2024-04-01  2163179
2024-05-01  2168211
2024-06-01  2143970
2024-07-01  2143139
2024-08-01  2162132
2024-09-01  2142427
2024-10-01  2176627
2024-11-01  2180323
2024-12-01  2192173

In [ ]:
px.line(TOTALCONSTRUCT, x=TOTALCONSTRUCT.index, y='TTLCONS')

### Existing Home Sales

In [ ]:
EXISTINGHOME = web.DataReader('EXHOSLUSM495S', 'fred', start)

In [ ]:
EXISTINGHOME

            EXHOSLUSM495S
DATE
2023-12-01        3880000
2024-01-01        4000000
2024-02-01        4380000
2024-03-01        4220000
2024-04-01        4140000
2024-05-01        4110000
2024-06-01        3900000
2024-07-01        3960000
2024-08-01        3880000
2024-09-01        3830000
2024-10-01        3960000
2024-11-01        4150000
2024-12-01        4240000

In [ ]:
px.line(EXISTINGHOME, x=EXISTINGHOME.index, y='EXHOSLUSM495S')

### New House Sales

In [ ]:
NEWHOUSESALES = web.DataReader('HSN1F', 'fred', start)

In [ ]:
NEWHOUSESALES

            HSN1F
DATE
2020-01-01    690
2020-02-01    707
2020-03-01    621
2020-04-01    579
2020-05-01    709
2020-06-01    896
2020-07-01    983
2020-08-01   1022
2020-09-01    979
2020-10-01   1031
2020-11-01    877
2020-12-01    878
2021-01-01    896
2021-02-01    774
2021-03-01    861
2021-04-01    837
2021-05-01    726
2021-06-01    689
2021-07-01    727
2021-08-01    691
2021-09-01    731
2021-10-01    683
2021-11-01    787
2021-12-01    834
2022-01-01    798
2022-02-01    781
2022-03-01    713
2022-04-01    636
2022-05-01    648
2022-06-01    543
2022-07-01    519
2022-08-01    644
2022-09-01    556
2022-10-01    577
2022-11-01    596
2022-12-01    632
2023-01-01    639
2023-02-01    625
2023-03-01    644
2023-04-01    687
2023-05-01    741
2023-06-01    666
2023-07-01    700
2023-08-01    652
2023-09-01    694
2023-10-01    673
2023-11-01    611
2023-12-01    654
2024-01-01    664
2024-02-01    643
2024-03-01    683
2024-04-01    736
2024-05-01    672
2024-06-01    672
2024-07-01    707
2024-08-01    691
2024-09-01    726
2024-10-01    615
2024-11-01    674
2024-12-01    698

In [ ]:
px.line(NEWHOUSESALES, x=NEWHOUSESALES.index, y='HSN1F')

### New House Sales e 30Y Mortgage Rate (Average)

In [ ]:
import pandas_datareader.data as web
import datetime
import plotly.graph_objects as go
from scipy.stats import zscore

start = datetime.datetime(2010, 1, 1)

# Fetch the data
NEWHOUSESALES = web.DataReader('HSN1F', 'fred', start)
MortgageRate = web.DataReader('MORTGAGE30US', 'fred', start)

# Normalize the data using z-scores
NEWHOUSESALES['HSN1F_zscore'] = zscore(NEWHOUSESALES['HSN1F'])
MortgageRate['MORTGAGE30US_zscore'] = zscore(MortgageRate['MORTGAGE30US'])

# Create the figure
fig = go.Figure()

# Add New House Sales trace (blue)
fig.add_trace(go.Scatter(
    x=NEWHOUSESALES.index,
    y=NEWHOUSESALES['HSN1F_zscore'],  # Using normalized data
    mode='lines',
    name='New House Sales',
    line=dict(color='blue')
))

# Add Mortgage Rate trace (dark orange)
fig.add_trace(go.Scatter(
    x=MortgageRate.index,
    y=MortgageRate['MORTGAGE30US_zscore'],  # Using normalized data
    mode='lines',
    name='Mortgage Rate',
    line=dict(color='darkorange')
))

# Update layout
fig.update_layout(
    title='New House Sales and Mortgage Rate (Normalized)',
    xaxis_title='Data',
    yaxis_title='Z-score'
)

# Show the figure
fig.show()

### Monthly Supply

In [ ]:
MONTHLY = web.DataReader('MSACSR', 'fred', start)

In [ ]:
MONTHLY

            MSACSR
DATE
2000-01-01     4.3
2000-02-01     4.3
2000-03-01     4.3
2000-04-01     4.4
2000-05-01     4.4
...            ...
2024-08-01     8.2
2024-09-01     7.8
2024-10-01     9.4
2024-11-01     8.7
2024-12-01     8.5

[300 rows x 1 columns]

In [ ]:
px.line(MONTHLY, x=MONTHLY.index, y='MSACSR')

### S&P/Case-Shiller Home Price Index

In [ ]:
CaseSchiller = web.DataReader('CSUSHPINSA', 'fred', start)

In [ ]:
CaseSchiller

            CSUSHPINSA
DATE
2000-01-01     100.000
2000-02-01     100.571
2000-03-01     101.466
2000-04-01     102.541
2000-05-01     103.702
...                ...
2024-08-01     325.138
2024-09-01     324.779
2024-10-01     324.211
2024-11-01     323.690
2024-12-01     323.219

[300 rows x 1 columns]

In [ ]:
px.line(CaseSchiller, x=CaseSchiller.index, y='CSUSHPINSA')

### S&P 500 Case Shiller MoM e YoY

S&P 500 Case Shiller MoM

In [ ]:
import pandas_datareader.data as web
import datetime
import plotly.express as px

start = datetime.datetime(2022, 1, 1)
CaseSchiller = web.DataReader('CSUSHPINSA', 'fred', start)

# Calcula a variação percentual mensal (MoM)
CaseSchiller['MoM_Change'] = CaseSchiller['CSUSHPINSA'].pct_change() * 100

# Formata a variação percentual para exibição (opcional)
CaseSchiller['MoM_Change_Text'] = CaseSchiller['MoM_Change'].apply(lambda x: f'{x:.2f}%')

# Cria o gráfico de barras com Plotly Express
fig = px.bar(CaseSchiller, x=CaseSchiller.index, y='MoM_Change', text='MoM_Change_Text',
             title='Case-Shiller Home Price Index (MoM Change)')

# Personaliza o gráfico para exibir os valores fora das barras
fig.update_traces(textposition='outside')

# Adiciona linha zero
fig.add_hline(y=0)

# Ajusta o layout (opcional)
fig.update_layout(yaxis_title='Variação Percentual (%)', xaxis_title='Data')

# Exibe o gráfico
fig.show()

 S&P 500 Case Shiller YoY

In [ ]:
import pandas_datareader.data as web
import datetime
import plotly.graph_objects as go
import numpy as np
from scipy.stats import zscore

start = datetime.datetime(2000, 1, 1)
CaseShiller = web.DataReader('CSUSHPINSA', 'fred', start)

# Calcula a variação percentual anual (YoY)
CaseShiller['YoY_Change'] = CaseShiller['CSUSHPINSA'].pct_change(periods=12) * 100

# Normaliza os dados usando zscore
CaseShiller['CSUSHPINSA_zscore'] = zscore(CaseShiller['CSUSHPINSA'])
CaseShiller['YoY_Change_zscore'] = zscore(CaseShiller['YoY_Change'])

# Cria o gráfico
fig = go.Figure()

# Adiciona o traço para o CaseShiller normalizado - Azul
fig.add_trace(go.Scatter(x=CaseShiller.index,
                         y=CaseShiller['CSUSHPINSA_zscore'],
                         mode='lines', name='CaseShiller (Normalizado)',
                         line=dict(color='blue')))

# Adiciona o traço para o CaseShiller em YoY - Laranja
fig.add_trace(go.Scatter(x=CaseShiller.index, y=CaseShiller['YoY_Change'],
                         mode='lines', name='CaseShiller YoY',
                         line=dict(color='darkorange')))

# Adiciona linha preta no 0
fig.add_shape(type='line',
              x0=CaseShiller.index.min(),
              y0=0,
              x1=CaseShiller.index.max(),
              y1=0,
              line=dict(color='black'))

# Configura o layout do gráfico
fig.update_layout(title='CaseShiller e CaseShiller YoY (Normalizados)',
                  xaxis_title='Data',
                  yaxis_title='Z-score')

# Exibe o gráfico
fig.show()

### Affordability Index Fixed

In [ ]:

Affordability = web.DataReader('FIXHAI', 'fred', start)

In [ ]:
Affordability

            FIXHAI
DATE
2023-12-01   100.5
2024-01-01   104.5
2024-02-01   102.1
2024-03-01   100.0
2024-04-01    95.1
2024-05-01    92.3
2024-06-01    91.6
2024-07-01    93.8
2024-08-01    99.1
2024-09-01   104.9
2024-10-01   102.4
2024-11-01    99.4
2024-12-01   100.7

In [ ]:
px.line(Affordability, x=Affordability.index, y='FIXHAI')

# <span style="color: gray;">**ECONOMIC** **ACTIVITY**</span>

###GDP Now

In [ ]:
import pandas as pd
import datetime
import plotly.express as px
from pandas_datareader import data as web

start = datetime.datetime(2000, 1, 1)
FinalSalesToPrivateDomestic = web.DataReader('GDPNOW', 'fred', start)

fig = px.line(FinalSalesToPrivateDomestic, x=FinalSalesToPrivateDomestic.index, y='GDPNOW', title='GDP NOW')

# Add a horizontal line at y=0
fig.add_shape(
    type="line",
    x0=FinalSalesToPrivateDomestic.index.min(),
    y0=0,
    x1=FinalSalesToPrivateDomestic.index.max(),
    y1=0,
    line=dict(color="black"),
)

fig.show()

### Real GDP e Real GDP YoY

Real GDP

In [ ]:
REALGDP = web.DataReader('GDPC1', 'fred', start)

In [ ]:
REALGDP

                GDPC1
DATE
2000-01-01  13878.147
2000-04-01  14130.908
2000-07-01  14145.312
2000-10-01  14229.765
2001-01-01  14183.120
...               ...
2023-10-01  22960.600
2024-01-01  23053.545
2024-04-01  23223.906
2024-07-01  23400.294
2024-10-01  23536.293

[100 rows x 1 columns]

In [ ]:
px.line(REALGDP, x=REALGDP.index, y='GDPC1')

Real GDP YoY

In [ ]:
import pandas_datareader.data as web
import datetime
import plotly.express as px

start = datetime.datetime(2018, 1, 1)
REALGDP = web.DataReader('GDPC1', 'fred', start)

# Calcula a variação percentual trimestral anualizada (YoY)
REALGDP['YoY_Change'] = REALGDP['GDPC1'].pct_change(periods=4) * 100
REALGDP['Quarter'] = REALGDP.index.to_period('Q')  # Cria uma coluna com o trimestre

# Agrupa por trimestre e calcula a média do YoY Change
quarterly_gdp = REALGDP.groupby('Quarter')['YoY_Change'].mean().reset_index()

# Converte a coluna 'Quarter' para string
quarterly_gdp['Quarter'] = quarterly_gdp['Quarter'].astype(str)

# Cria o gráfico de barras com Plotly Express
fig_yoy = px.bar(quarterly_gdp, x='Quarter', y='YoY_Change', title='REALGDP YoY Trimestral',
                  color_discrete_sequence=['blue'])
fig_yoy.update_traces(texttemplate='%{y:.2f}%', textposition='outside') # valor acima
fig_yoy.update_layout(xaxis_title='Trimestre', yaxis_title='Variação Percentual Anual Média (%)')
fig_yoy.show()

### Real Final Sales to Private Domestic Purchasers e Real Final Sales to Private DPP QoQ Annualized

In [ ]:
import pandas as pd
import datetime
import plotly.express as px
from pandas_datareader import data as web



start = datetime.datetime(2000, 1, 1)
FinalSalesToPrivateDomestic= web.DataReader('LB0000031Q020SBEA', 'fred', start)
px.line(FinalSalesToPrivateDomestic, x=FinalSalesToPrivateDomestic.index, y='LB0000031Q020SBEA', title='Real Final Sales to Private Domestic Purchasers')  # Plota o gráfico

Real Final Sales to Private DPP QoQ Annualized

In [ ]:
import pandas as pd
import datetime
import plotly.express as px
from pandas_datareader import data as web

# Coletar dados
start = datetime.datetime(2017, 1, 1)
FinalSalesToPrivateDomestic = web.DataReader('LB0000031Q020SBEA', 'fred', start)

# Calcular a variação percentual trimestral anualizada (QoQ Annualized)
FinalSalesToPrivateDomestic['QoQ_Annualized'] = (
    (FinalSalesToPrivateDomestic['LB0000031Q020SBEA'] / FinalSalesToPrivateDomestic['LB0000031Q020SBEA'].shift(1) - 1) * 4
) * 100  # Multiplicar por 100 para obter a porcentagem

# Converter o índice para data trimestral
FinalSalesToPrivateDomestic.index = FinalSalesToPrivateDomestic.index.to_period('Q')

# Converter o índice para string antes de plotar
FinalSalesToPrivateDomestic.index = FinalSalesToPrivateDomestic.index.astype(str)

# Criar uma nova coluna com os valores formatados como porcentagem
FinalSalesToPrivateDomestic['QoQ_Percentual_Text'] = FinalSalesToPrivateDomestic['QoQ_Annualized'].apply(lambda x: f'{x:.2f}%')

# Calcular a média de 'QoQ_Annualized'
media_qoq = FinalSalesToPrivateDomestic['QoQ_Annualized'].mean()

# Criar o histograma
fig = px.histogram(FinalSalesToPrivateDomestic,
                   x=FinalSalesToPrivateDomestic.index,
                   y='QoQ_Annualized',
                   title='Real Final Sales to Private DPP QoQ Annualized & Average Real Final Sales to DPP')

# Customizar o histograma
fig.update_layout(xaxis_title='Data Trimestral',
                  yaxis_title='Variação Percentual (%)')
fig.update_xaxes(type='category')  # Definir o eixo x como categórico para datas trimestrais

# Adicionar texto com fig.update_traces()
fig.update_traces(text=FinalSalesToPrivateDomestic['QoQ_Percentual_Text'], textposition="outside")

# Adicionar a linha da média em laranja
fig.add_shape(type='line',
              x0=FinalSalesToPrivateDomestic.index[0],
              y0=media_qoq,
              x1=FinalSalesToPrivateDomestic.index[-1],
              y1=media_qoq,
              line=dict(color='orange', width=2))

# Exibir o histograma
fig.show()

### Real PCE, Real PCE MoM e Real PCE YoY

Real PCE

In [ ]:
REALPCE = web.DataReader('PCEC96', 'fred', start)

In [ ]:
REALPCE

             PCEC96
DATE
2020-01-01  14217.4
2020-02-01  14191.1
2020-03-01  13249.3
2020-04-01  11786.8
2020-05-01  12755.2
2020-06-01  13473.5
2020-07-01  13682.1
2020-08-01  13783.9
2020-09-01  13973.0
2020-10-01  14013.4
2020-11-01  13977.9
2020-12-01  14032.9
2021-01-01  14221.4
2021-02-01  14078.8
2021-03-01  14685.5
2021-04-01  14791.6
2021-05-01  14748.9
2021-06-01  14886.8
2021-07-01  14851.6
2021-08-01  14943.5
2021-09-01  14977.9
2021-10-01  15079.2
2021-11-01  15113.7
2021-12-01  15067.9
2022-01-01  15093.0
2022-02-01  15101.9
2022-03-01  15175.2
2022-04-01  15234.1
2022-05-01  15207.7
2022-06-01  15217.8
2022-07-01  15210.5
2022-08-01  15297.4
2022-09-01  15324.8
2022-10-01  15350.3
2022-11-01  15305.5
2022-12-01  15316.2
2023-01-01  15524.8
2023-02-01  15521.4
2023-03-01  15484.4
2023-04-01  15536.7
2023-05-01  15546.1
2023-06-01  15562.7
2023-07-01  15631.6
2023-08-01  15634.7
2023-09-01  15673.7
2023-10-01  15706.1
2023-11-01  15774.0
2023-12-01  15864.0
2024-01-01  15812.6
2024-02-01  15848.8
2024-03-01  15909.2
2024-04-01  15908.3
2024-05-01  15985.9
2024-06-01  16007.7
2024-07-01  16077.1
2024-08-01  16088.6
2024-09-01  16173.4
2024-10-01  16207.6
2024-11-01  16283.6
2024-12-01  16349.2

In [ ]:
px.line(REALPCE, x=REALPCE.index, y='PCEC96')

Real PCE MoM

In [ ]:
import pandas_datareader.data as web
import datetime
import plotly.express as px

start = datetime.datetime(2022, 1, 1)  # Define a data de início

# Obtém os dados do Real PCE do FRED
realpce = web.DataReader('PCEC96', 'fred', start)

# Calcula a variação percentual mensal (MoM)
realpce['MoM_Change'] = realpce['PCEC96'].pct_change() * 100

# Formata a variação percentual para exibição (opcional)
realpce['MoM_Change_Text'] = realpce['MoM_Change'].apply(lambda x: f'{x:.2f}%')

# Cria o gráfico de barras com Plotly Express
fig = px.bar(realpce, x=realpce.index, y='MoM_Change', text='MoM_Change_Text',
             title='Real PCE (MoM Change)',
             color_discrete_sequence=['blue'])  # Define a cor das barras como azul


# Personaliza o gráfico para exibir os valores fora das barras
fig.update_traces(textposition='outside')

# Adiciona linha zero
fig.add_hline(y=0)

# Ajusta o layout (opcional)
fig.update_layout(yaxis_title='Variação Percentual (%)', xaxis_title='Data')

# Exibe o gráfico
fig.show()

 Real PCE YoY

In [ ]:
import pandas_datareader.data as web
import datetime
import plotly.express as px

start = datetime.datetime(2008, 1, 1)  # Define a data de início

# Obtém os dados do Real PCE do FRED
realpce = web.DataReader('PCEC96', 'fred', start)

# Calcula a variação percentual anual (YoY)
realpce['YoY_Change'] = realpce['PCEC96'].pct_change(periods=12) * 100

# Cria o gráfico de linha com Plotly Express
# Removed 'line_color' and replaced it with 'color_discrete_sequence'
fig = px.line(realpce, x=realpce.index, y='YoY_Change',
              title='Real PCE (YoY Change)',
              labels={'YoY_Change': 'YoY Change (%)'},  # Rótulo do eixo y
              color_discrete_sequence=['blue'])  # Define a cor da linha como azul

# Adiciona linha horizontal no zero
fig.add_shape(type='line', x0=realpce.index.min(), y0=0, x1=realpce.index.max(), y1=0,
              line=dict(color='black', dash='dash'))  # Linha tracejada preta

# Personaliza o layout do gráfico (opcional)
fig.update_layout(xaxis_title='Data',
                  yaxis_title='Variação Percentual Anual (%)')

# Exibe o gráfico
fig.show()

### Industrial Production - US, Industrial Production MoM e Industrial Production YoY

Industrial Production - US

In [ ]:
IndustrialProduction = web.DataReader('indpro', 'fred', start)

In [ ]:
IndustrialProduction

              indpro
DATE
2020-01-01  101.3372
2020-02-01  101.6718
2020-03-01   97.6060
2020-04-01   84.6812
2020-05-01   86.0108
2020-06-01   91.6745
2020-07-01   95.0037
2020-08-01   95.9294
2020-09-01   95.8914
2020-10-01   96.5256
2020-11-01   96.9529
2020-12-01   98.2039
2021-01-01   98.8135
2021-02-01   95.5072
2021-03-01   98.1929
2021-04-01   98.3317
2021-05-01   99.1867
2021-06-01   99.6483
2021-07-01  100.0668
2021-08-01  100.0412
2021-09-01   98.9955
2021-10-01  100.3542
2021-11-01  101.2684
2021-12-01  101.1948
2022-01-01  101.2146
2022-02-01  101.8458
2022-03-01  102.6732
2022-04-01  102.9024
2022-05-01  102.9659
2022-06-01  102.8224
2022-07-01  103.0505
2022-08-01  103.1703
2022-09-01  103.5326
2022-10-01  103.4442
2022-11-01  103.1058
2022-12-01  101.8266
2023-01-01  102.7476
2023-02-01  102.8003
2023-03-01  102.8143
2023-04-01  103.2241
2023-05-01  102.9809
2023-06-01  102.3809
2023-07-01  103.0722
2023-08-01  103.0951
2023-09-01  103.3081
2023-10-01  102.5781
2023-11-01  102.8868
2023-12-01  102.6309
2024-01-01  101.4830
2024-02-01  102.7267
2024-03-01  102.5186
2024-04-01  102.3568
2024-05-01  102.9797
2024-06-01  103.2534
2024-07-01  102.5192
2024-08-01  103.0135
2024-09-01  102.5969
2024-10-01  102.0854
2024-11-01  102.2549
2024-12-01  103.1942

In [ ]:
px.line(IndustrialProduction, x=IndustrialProduction.index, y='indpro')

 Industrial Production MoM

In [ ]:
import pandas_datareader.data as web
import datetime
import plotly.express as px

start = datetime.datetime(2022, 1, 1)  # Define a data de início

# Obtém os dados do Industrial Production do FRED
IndustrialProduction = web.DataReader('INDPRO', 'fred', start)

# Calcula a variação percentual mensal (MoM)
IndustrialProduction['MoM_Change'] = IndustrialProduction['INDPRO'].pct_change() * 100

# Formata a variação percentual para exibição (opcional)
IndustrialProduction['MoM_Change_Text'] = IndustrialProduction['MoM_Change'].apply(lambda x: f'{x:.2f}%')

# Cria o gráfico de barras com Plotly Express
fig = px.bar(IndustrialProduction, x=IndustrialProduction.index, y='MoM_Change', text='MoM_Change_Text',
             title='Industrial Production (MoM Change)',
             color_discrete_sequence=['blue'])  # Define a cor das barras como azul

# Personaliza o gráfico para exibir os valores fora das barras em cima
fig.update_traces(textposition='outside')

# Adiciona linha zero
fig.add_hline(y=0)

# Ajusta o layout (opcional)
fig.update_layout(yaxis_title='Variação Percentual (%)', xaxis_title='Data')

# Exibe o gráfico
fig.show()

 Industrial Production YoY

In [ ]:
import pandas_datareader.data as web
import datetime
import plotly.express as px

start = datetime.datetime(2019, 1, 1)  # Define a data de início

# Obtém os dados do Industrial Production do FRED
IndustrialProduction = web.DataReader('INDPRO', 'fred', start)

# Calcula a variação percentual anual (YoY)
IndustrialProduction['YoY_Change'] = IndustrialProduction['INDPRO'].pct_change(periods=12) * 100

# Cria o gráfico de linha com Plotly Express
fig = px.line(IndustrialProduction, x=IndustrialProduction.index, y='YoY_Change',
              title='Industrial Production (YoY Change)',
              color_discrete_sequence=['blue'])  # Define a cor da linha como azul

# Adiciona linha horizontal no zero
fig.add_shape(type='line', x0=IndustrialProduction.index.min(), y0=0,
              x1=IndustrialProduction.index.max(), y1=0,
              line=dict(color='black'))  # Linha sólida preta

# Ajusta o layout (opcional)
fig.update_layout(yaxis_title='Variação Percentual Anual (%)', xaxis_title='Data')

# Exibe o gráfico
fig.show()

### Retail Sales e Retail Sales MoM

Retail Sales

In [ ]:
import pandas_datareader.data as web
import datetime
import plotly.express as px

start = datetime.datetime(2008, 1, 1)
RETAILSALES = web.DataReader('RSAFS', 'fred', start)
px.line(RETAILSALES, x=RETAILSALES.index, y='RSAFS', title='RETAIL SALES')  # Plota o gráfico

Retail Sales MoM

In [ ]:
import pandas_datareader.data as web
import datetime
import plotly.express as px

start = datetime.datetime(2022, 1, 1)  # Define a data de início

# Obtém os dados do Retail Sales do FRED
RETAILSALES = web.DataReader('RSAFS', 'fred', start)

# Calcula a variação percentual mensal (MoM)
RETAILSALES['MoM_Change'] = RETAILSALES['RSAFS'].pct_change() * 100

# Formata a variação percentual para exibição (opcional)
RETAILSALES['MoM_Change_Text'] = RETAILSALES['MoM_Change'].apply(lambda x: f'{x:.2f}%')

# Cria o gráfico de barras com Plotly Express
fig = px.bar(RETAILSALES, x=RETAILSALES.index, y='MoM_Change', text='MoM_Change_Text',
             title='Retail Sales (MoM Change)',
             color_discrete_sequence=['blue'])  # Define a cor das barras como azul

# Personaliza o gráfico para exibir os valores fora das barras
fig.update_traces(textposition='outside')

# Adiciona linha zero
fig.add_hline(y=0)

# Ajusta o layout (opcional)
fig.update_layout(yaxis_title='Variação Percentual (%)', xaxis_title='Data')

# Exibe o gráfico
fig.show()

### Real Retail Sales, Core Real Retail e Real Retail Sales MoM

Real Retail Sales

In [ ]:
REALRETAIL = web.DataReader('RRSFS', 'fred', start)

In [ ]:
REALRETAIL

             RRSFS
DATE
2020-01-01  202762
2020-02-01  202654
2020-03-01  185091
2020-04-01  159477
2020-05-01  189591
2020-06-01  205013
2020-07-01  207331
2020-08-01  208403
2020-09-01  211976
2020-10-01  210999
2020-11-01  208662
2020-12-01  209620
2021-01-01  217222
2021-02-01  210753
2021-03-01  232719
2021-04-01  233551
2021-05-01  229335
2021-06-01  229812
2021-07-01  225267
2021-08-01  226173
2021-09-01  226518
2021-10-01  228028
2021-11-01  228737
2021-12-01  225250
2022-01-01  227943
2022-02-01  228634
2022-03-01  231041
2022-04-01  233294
2022-05-01  230361
2022-06-01  228996
2022-07-01  227527
2022-08-01  228724
2022-09-01  227147
2022-10-01  228791
2022-11-01  225529
2022-12-01  223131
2023-01-01  230924
2023-02-01  227691
2023-03-01  225123
2023-04-01  225749
2023-05-01  226388
2023-06-01  226508
2023-07-01  226726
2023-08-01  227426
2023-09-01  228422
2023-10-01  227323
2023-11-01  226289
2023-12-01  227273
2024-01-01  224546
2024-02-01  225231
2024-03-01  225480
2024-04-01  224487
2024-05-01  224918
2024-06-01  224299
2024-07-01  226699
2024-08-01  226032
2024-09-01  227532
2024-10-01  228287
2024-11-01  229397
2024-12-01  229592

In [ ]:
px.line(REALRETAIL, x=REALRETAIL.index, y='RRSFS')

 Core Real Retail

In [ ]:
COREREALRETAIL = web.DataReader('MARTSSM44W72USS', 'fred', start)

In [ ]:
COREREALRETAIL

            MARTSSM44W72USS
DATE
2020-01-01           379692
2020-02-01           380935
2020-03-01           366704
2020-04-01           315773
2020-05-01           356539
2020-06-01           386277
2020-07-01           393671
2020-08-01           396885
2020-09-01           403675
2020-10-01           402484
2020-11-01           399673
2020-12-01           399082
2021-01-01           415290
2021-02-01           403048
2021-03-01           439343
2021-04-01           443581
2021-05-01           439721
2021-06-01           448968
2021-07-01           443068
2021-08-01           449334
2021-09-01           450379
2021-10-01           456495
2021-11-01           460271
2021-12-01           456588
2022-01-01           461534
2022-02-01           464933
2022-03-01           472381
2022-04-01           478548
2022-05-01           478988
2022-06-01           482188
2022-07-01           481596
2022-08-01           487096
2022-09-01           489000
2022-10-01           492671
2022-11-01           488240
2022-12-01           487832
2023-01-01           503651
2023-02-01           500695
2023-03-01           495044
2023-04-01           498721
2023-05-01           502159
2023-06-01           503189
2023-07-01           506510
2023-08-01           507769
2023-09-01           510161
2023-10-01           511606
2023-11-01           511370
2023-12-01           516751
2024-01-01           512510
2024-02-01           513449
2024-03-01           516452
2024-04-01           515914
2024-05-01           517324
2024-06-01           521259
2024-07-01           523859
2024-08-01           523935
2024-09-01           530276
2024-10-01           531231
2024-11-01           532358
2024-12-01           533894

In [ ]:
px.line(COREREALRETAIL, x=COREREALRETAIL.index, y='MARTSSM44W72USS')

Real Retail Sales MoM

In [ ]:
import pandas_datareader.data as web
import datetime
import plotly.express as px

start = datetime.datetime(2022, 1, 1)  # Define a data de início

# Obtém os dados do Real Retail Sales do FRED
REALRETAIL = web.DataReader('RRSFS', 'fred', start)

# Calcula a variação percentual mensal (MoM)
REALRETAIL['MoM_Change'] = REALRETAIL['RRSFS'].pct_change() * 100

# Formata a variação percentual para exibição (opcional)
REALRETAIL['MoM_Change_Text'] = REALRETAIL['MoM_Change'].apply(lambda x: f'{x:.2f}%')

# Cria o gráfico de barras com Plotly Express
fig = px.bar(REALRETAIL, x=REALRETAIL.index, y='MoM_Change', text='MoM_Change_Text',
             title='Real Retail Sales (MoM Change)',
             color_discrete_sequence=['blue'])  # Define a cor das barras como azul

# Personaliza o gráfico para exibir os valores fora das barras
fig.update_traces(textposition='outside')

# Adiciona linha zero
fig.add_hline(y=0)

# Ajusta o layout (opcional)
fig.update_layout(yaxis_title='Variação Percentual (%)', xaxis_title='Data')

# Exibe o gráfico
fig.show()

### RetailSales e RealRetailSales YoY

In [ ]:
import pandas_datareader.data as web
import datetime
import plotly.graph_objects as go

start = datetime.datetime(2019, 1, 1)  # Define a data de início

# Obtém os dados do Retail Sales e Real Retail Sales do FRED
RetailSales = web.DataReader('RSAFS', 'fred', start)
RealRetailSales = web.DataReader('RRSFS', 'fred', start)

# Calcula a variação percentual anual (YoY) para ambos
RetailSales['YoY_Change'] = RetailSales['RSAFS'].pct_change(periods=12) * 100
RealRetailSales['YoY_Change'] = RealRetailSales['RRSFS'].pct_change(periods=12) * 100

# Cria o gráfico com Plotly Graph Objects
fig = go.Figure()

# Adiciona o traço para Retail Sales (laranja escuro)
fig.add_trace(go.Scatter(x=RetailSales.index, y=RetailSales['YoY_Change'],
                         mode='lines',
                         name='Retail Sales YoY',
                         line=dict(color='darkorange')))

# Adiciona o traço para Real Retail Sales (azul)
fig.add_trace(go.Scatter(x=RealRetailSales.index, y=RealRetailSales['YoY_Change'],
                         mode='lines',
                         name='Real Retail Sales YoY',
                         line=dict(color='blue')))

# Adiciona linha horizontal no zero (sólida e preta)
fig.add_shape(type='line',
              x0=RetailSales.index.min(),
              y0=0,
              x1=RetailSales.index.max(),
              y1=0,
              line=dict(color='black', width=2))  # width=2 para torná-la mais visível

# Personaliza o layout do gráfico (opcional)
fig.update_layout(title='Retail Sales vs. Real Retail Sales (YoY Change)',
                  xaxis_title='Data',
                  yaxis_title='Variação Percentual Anual (%)',
                  legend_title_text='')

# Exibe o gráfico
fig.show()

### Consumer Sentiment (University of Michigan)

In [ ]:
consumersentiment = web.DataReader('UMCSENT', 'fred', start)

In [ ]:
consumersentiment

            UMCSENT
DATE
2020-01-01     99.8
2020-02-01    101.0
2020-03-01     89.1
2020-04-01     71.8
2020-05-01     72.3
2020-06-01     78.1
2020-07-01     72.5
2020-08-01     74.1
2020-09-01     80.4
2020-10-01     81.8
2020-11-01     76.9
2020-12-01     80.7
2021-01-01     79.0
2021-02-01     76.8
2021-03-01     84.9
2021-04-01     88.3
2021-05-01     82.9
2021-06-01     85.5
2021-07-01     81.2
2021-08-01     70.3
2021-09-01     72.8
2021-10-01     71.7
2021-11-01     67.4
2021-12-01     70.6
2022-01-01     67.2
2022-02-01     62.8
2022-03-01     59.4
2022-04-01     65.2
2022-05-01     58.4
2022-06-01     50.0
2022-07-01     51.5
2022-08-01     58.2
2022-09-01     58.6
2022-10-01     59.9
2022-11-01     56.7
2022-12-01     59.8
2023-01-01     64.9
2023-02-01     66.9
2023-03-01     62.0
2023-04-01     63.7
2023-05-01     59.0
2023-06-01     64.2
2023-07-01     71.5
2023-08-01     69.4
2023-09-01     67.8
2023-10-01     63.8
2023-11-01     61.3
2023-12-01     69.7
2024-01-01     79.0
2024-02-01     76.9
2024-03-01     79.4
2024-04-01     77.2
2024-05-01     69.1
2024-06-01     68.2
2024-07-01     66.4
2024-08-01     67.9
2024-09-01     70.1
2024-10-01     70.5
2024-11-01     71.8
2024-12-01     74.0

In [ ]:
px.line(consumersentiment, x=consumersentiment.index, y='UMCSENT')

### Global Economic Policy Uncertainty Index: Current Price Adjusted GDP

In [ ]:
import pandas as pd
import datetime
import plotly.express as px
from pandas_datareader import data as web



start = datetime.datetime(2000, 1, 1)
MortgageRate = web.DataReader('GEPUCURRENT', 'fred', start)
px.line(MortgageRate, x=MortgageRate.index, y='GEPUCURRENT', title='Global Economic Policy Uncertainty Index GDP')  # Plota o gráfico

# <span style="color: gray;">**LABOR** **MARKET**</span>

### Taxa de Desemprego (UnemPloyment Rate )

In [ ]:
Unrate = web.DataReader('UNRATE', 'fred', start)

In [ ]:
Unrate

            UNRATE
DATE
2000-01-01     4.0
2000-02-01     4.1
2000-03-01     4.0
2000-04-01     3.8
2000-05-01     4.0
...            ...
2024-09-01     4.1
2024-10-01     4.1
2024-11-01     4.2
2024-12-01     4.1
2025-01-01     4.0

[301 rows x 1 columns]

In [ ]:
px.line(Unrate, x=Unrate.index, y='UNRATE')

### Unemployment Rate e U.Rate 12m

In [ ]:
import pandas_datareader.data as web
import datetime
import plotly.graph_objects as go

start = datetime.datetime(2007, 1, 1)
Unrate = web.DataReader('UNRATE', 'fred', start)

Unrate['12m_Avg'] = Unrate['UNRATE'].rolling(window=12).mean()

fig = go.Figure()
fig.add_trace(go.Scatter(x=Unrate.index, y=Unrate['UNRATE'], name='Unrate', line=dict(color='blue')))
fig.add_trace(go.Scatter(x=Unrate.index, y=Unrate['12m_Avg'], name='12m Avg', line=dict(color='darkorange')))
fig.update_layout(title='Unrate e Média de 12 Meses',
                  yaxis_title='Taxa de Desemprego', xaxis_title='Data')
fig.show()

### Initial Calims - US

Initial Calims - US

In [ ]:
PedidosIniciais = web.DataReader('ICSA', 'fred', start)

In [ ]:
PedidosIniciais

              ICSA
DATE
2007-01-06  330000
2007-01-13  296000
2007-01-20  335000
2007-01-27  308000
2007-02-03  310000
...            ...
2025-01-18  223000
2025-01-25  208000
2025-02-01  220000
2025-02-08  214000
2025-02-15  219000

[946 rows x 1 columns]

In [ ]:
px.line(PedidosIniciais, x=PedidosIniciais.index, y='ICSA')

### Initial Claims (Average) e JOLTs

In [ ]:
from scipy.stats import zscore

PedidosIniciais['ICSA_zscore'] = zscore(PedidosIniciais['ICSA'])
Jolts['JTSJOL_zscore'] = zscore(Jolts['JTSJOL'])

fig = go.Figure()
fig.add_trace(go.Scatter(x=PedidosIniciais.index, y=PedidosIniciais['ICSA_zscore'], name='PedidosIniciais', line=dict(color='blue')))
fig.add_trace(go.Scatter(x=Jolts.index, y=Jolts['JTSJOL_zscore'], name='Jolts', line=dict(color='darkorange')))
fig.update_layout(title='PedidosIniciais e Jolts (Padronizados)',
                  yaxis_title='Valor Padronizado (Z-score)', xaxis_title='Data')
fig.show()

### JOLTs e JOLTs MoM

JOLTs

In [ ]:
Jolts = web.DataReader('JTSJOL', 'fred', start )

In [ ]:
Jolts

            JTSJOL
DATE
2020-01-01    7170
2020-02-01    6974
2020-03-01    5924
2020-04-01    4637
2020-05-01    5593
2020-06-01    6156
2020-07-01    6491
2020-08-01    6369
2020-09-01    6505
2020-10-01    6838
2020-11-01    6857
2020-12-01    6758
2021-01-01    7185
2021-02-01    7818
2021-03-01    8519
2021-04-01    9282
2021-05-01    9905
2021-06-01   10317
2021-07-01   10991
2021-08-01   10884
2021-09-01   10875
2021-10-01   11365
2021-11-01   11178
2021-12-01   11511
2022-01-01   11243
2022-02-01   11700
2022-03-01   12182
2022-04-01   11773
2022-05-01   11473
2022-06-01   11204
2022-07-01   11537
2022-08-01   10119
2022-09-01   10784
2022-10-01   10526
2022-11-01   10702
2022-12-01   11000
2023-01-01   10425
2023-02-01    9849
2023-03-01    9623
2023-04-01    9904
2023-05-01    9311
2023-06-01    9125
2023-07-01    8805
2023-08-01    9358
2023-09-01    9307
2023-10-01    8685
2023-11-01    8931
2023-12-01    8889
2024-01-01    8748
2024-02-01    8813
2024-03-01    8355
2024-04-01    7919
2024-05-01    8230
2024-06-01    7910
2024-07-01    7711
2024-08-01    7861
2024-09-01    7372
2024-10-01    7839
2024-11-01    8156
2024-12-01    7600

In [ ]:
px.line(Jolts, x=Jolts.index, y='JTSJOL')

 JOLTs Month

In [ ]:
import pandas_datareader.data as web
import datetime
import plotly.express as px

start = datetime.datetime(2020, 1, 1)
Jolts = web.DataReader('JTSJOL', 'fred', start)

# Calcular a diferença entre o valor atual e o anterior
Jolts['Diff'] = Jolts['JTSJOL'].diff()

# Criar uma coluna 'text' com os valores para exibir nas barras
Jolts['text'] = Jolts['Diff'].astype(str)

# Criar o gráfico de barras
fig = px.bar(Jolts,
             x=Jolts.index,
             y='Diff',
             title='JOLTs Month',
             text='text')

# Configurar a aparência do texto nas barras
fig.update_traces(textfont_size=12,
                  textangle=0,
                  textposition="outside",
                  cliponaxis=False)

# Configurar os títulos dos eixos
fig.update_layout(yaxis_title='Variação',
                  xaxis_title='Data')

# Exibir o gráfico
fig.show()

### Unemployment Level

In [ ]:
import pandas_datareader.data as web
import datetime
import plotly.express as px

start = datetime.datetime(2015, 1, 1)
UnemploymentLevel = web.DataReader('UNEMPLOY', 'fred', start)
px.line(UnemploymentLevel, x=UnemploymentLevel.index, y='UNEMPLOY', title='Unemployment Level')  # Plota o gráfico

### JOLTs/Unemployment

In [ ]:
import pandas_datareader.data as web
import datetime
import plotly.express as px
import pandas as pd

start = datetime.datetime(2020, 1, 1)
Jolts = web.DataReader('JTSJOL', 'fred', start)
UnemploymentLevel = web.DataReader('UNEMPLOY', 'fred', start)

df = pd.DataFrame(index=Jolts.index)
df['JOLTS'] = Jolts['JTSJOL']
df['UnemploymentLevel'] = UnemploymentLevel['UNEMPLOY']
df['JOLTS/UnemploymentLevel'] = df['JOLTS'] / df['UnemploymentLevel']

# Change the title here:
fig = px.line(df, x=df.index, y='JOLTS/UnemploymentLevel', title='JOLTS/UnemploymentLevel')
fig.show()

### JOLTS/Unemployment E Wage Growth Tracker

In [ ]:
import pandas_datareader.data as web
import datetime
import plotly.express as px
import pandas as pd
from scipy.stats import zscore  # Import zscore for normalization

start = datetime.datetime(2007, 1, 1) # Changed to 2007 for more historical data

# Fetching the data
Jolts = web.DataReader('JTSJOL', 'fred', start)
UnemploymentLevel = web.DataReader('UNEMPLOY', 'fred', start)
WageGrowthTracker = web.DataReader('FRBATLWGT3MMAUMHWGO', 'fred', start)

# Creating the DataFrame
df = pd.DataFrame(index=Jolts.index)
df['JOLTS'] = Jolts['JTSJOL']
df['UnemploymentLevel'] = UnemploymentLevel['UNEMPLOY']
df['JOLTS/UnemploymentLevel'] = df['JOLTS'] / df['UnemploymentLevel']
df['WageGrowthTracker'] = WageGrowthTracker['FRBATLWGT3MMAUMHWGO']

# Normalize the data using z-scores
df['JOLTS/UnemploymentLevel_zscore'] = zscore(df['JOLTS/UnemploymentLevel'])
df['WageGrowthTracker_zscore'] = zscore(df['WageGrowthTracker'])

# Plotting the normalized data
fig = px.line(df, x=df.index, y=['JOLTS/UnemploymentLevel_zscore', 'WageGrowthTracker_zscore'],
              title='JOLTS/UnemploymentLevel vs. Wage Growth Tracker (Normalized)')

# Customizing colors
fig.update_traces(selector=dict(name='JOLTS/UnemploymentLevel_zscore'), line=dict(color='blue'))
fig.update_traces(selector=dict(name='WageGrowthTracker_zscore'), line=dict(color='darkorange'))

fig.show() # Corrected to fig.show()

### Payroll - Vagas de Emprego (All Employess, Total Nonfarm)

In [ ]:
Payroll = web.DataReader('PAYEMS', 'fred', start )

In [ ]:
Payroll

            PAYEMS
DATE
2020-01-01  152031
2020-02-01  152292
2020-03-01  150895
2020-04-01  130424
2020-05-01  133040
...            ...
2024-09-01  158314
2024-10-01  158358
2024-11-01  158619
2024-12-01  158926
2025-01-01  159069

[61 rows x 1 columns]

In [ ]:
px.line(Payroll, x=Payroll.index, y='PAYEMS')

### Payroll Calculado

In [ ]:
import pandas_datareader.data as web
import datetime
import plotly.express as px  # Import plotly.express for line chart

# Definir a data de início
start = datetime.datetime(2022, 1, 1)

# Coletar dados do Payroll (PAYEMS)
Payroll = web.DataReader('PAYEMS', 'fred', start)

# Calcular a diferença entre o valor atual e o valor do mês passado
Payroll['Diff'] = Payroll['PAYEMS'].diff()

# Multiplicar a diferença por 1000 para obter o novo valor do Payroll
Payroll['PAYEMS'] = Payroll['Diff'] * 1000

# Remover a primeira linha que contém um valor NaN na coluna 'Diff'
Payroll = Payroll.dropna()

# Criar o gráfico de linha com Plotly Express
fig = px.bar(Payroll, x=Payroll.index, y='PAYEMS', title='Payroll', text_auto='.2s')


# Formatar eixo x para mostrar ano e mês
fig.update_xaxes(
    tickformat="%Y-%m",  # Formato para ano e mês (YYYY-MM)
    dtick="M1",          # Intervalo de ticks mensal
    title_text="Data"     # Título do eixo x (opcional)
)

# Configurar layout do gráfico
fig.update_layout(yaxis_title='Valor')
# Change 'clipon' to 'cliponaxis'
fig.update_traces(textfont_size=12, textangle=0, textposition="outside", cliponaxis=False)

# Exibir o gráfico
fig.show()

### Payroll e Média de 3 Meses

In [ ]:
import pandas_datareader.data as web
import datetime
import plotly.graph_objects as go

# Definir a data de início
start = datetime.datetime(2022, 1, 1)

# Coletar dados do Payroll (PAYEMS)
Payroll = web.DataReader('PAYEMS', 'fred', start)

# Calcular a diferença entre o valor atual e o valor do mês passado
Payroll['Diff'] = Payroll['PAYEMS'].diff()

# Multiplicar a diferença por 1000 para obter o novo valor do Payroll
Payroll['PAYEMS'] = Payroll['Diff'] * 1000

# Remover a primeira linha que contém um valor NaN na coluna 'Diff'
Payroll = Payroll.dropna()


# Calcular a média móvel de 3 meses
Payroll['Média_Movel_3_Meses'] = Payroll['PAYEMS'].rolling(window=3).mean()

# Criar o gráfico
fig = go.Figure()

# Adicionar traço de barras para o Payroll com os números em cima
fig.add_trace(go.Bar(x=Payroll.index, y=Payroll['PAYEMS'], name='Payroll',
                     text=Payroll['PAYEMS'], textposition='outside'))

# Adicionar traço de linha para a média móvel
fig.add_trace(go.Scatter(x=Payroll.index, y=Payroll['Média_Movel_3_Meses'], name='Média Móvel 3 Meses'))

# Formatar eixo x para mostrar ano e mês
fig.update_xaxes(
    tickformat="%Y-%m",  # Formato para ano e mês (YYYY-MM)
    dtick="M1",          # Intervalo de ticks mensal
    title_text="Data"     # Título do eixo x (opcional)
)

# Configurar layout do gráfico
fig.update_layout(title='Payroll e Média Móvel de 3 Meses',
                  yaxis_title='Valor',
                  barmode='group')  # Para garantir que as barras não se sobreponham à linha

# Exibir o gráfico
fig.show()

### Sahm Rule

In [ ]:
SahmRule = web.DataReader('SAHMREALTIME', 'fred', start )

In [ ]:
SahmRule

            SAHMREALTIME
DATE
2007-01-01          0.07
2007-02-01          0.07
2007-03-01          0.03
2007-04-01          0.00
2007-05-01          0.00
...                  ...
2024-09-01          0.50
2024-10-01          0.43
2024-11-01          0.43
2024-12-01          0.40
2025-01-01          0.37

[217 rows x 1 columns]

In [ ]:
fig = px.line(SahmRule, x=SahmRule.index, y='SAHMREALTIME', title='Sahm Rule e Linha Indicativa de Crise 0.5')

# Adicionar linha pontilhada em 0.5
fig.add_shape(
    type="line",
    x0=SahmRule.index.min(),
    y0=0.5,
    x1=SahmRule.index.max(),
    y1=0.5,
    line=dict(color="black", dash="dot"),
)

fig.show()

### Real Disposable Income Less Gov. Transfers

In [ ]:
RDILessGovTransf = web.DataReader('W875RX1', 'fred', start )

In [ ]:
RDILessGovTransf

            W875RX1
DATE
2007-01-01  11666.7
2007-02-01  11713.7
2007-03-01  11765.5
2007-04-01  11801.5
2007-05-01  11811.5
...             ...
2024-08-01  16322.1
2024-09-01  16333.7
2024-10-01  16397.9
2024-11-01  16432.8
2024-12-01  16457.8

[216 rows x 1 columns]

In [ ]:
px.line(RDILessGovTransf, x=RDILessGovTransf.index, y='W875RX1', title='Real Disposable Income Less Gov. Transfers')

### Real Disposable Income Less Gov. Transfer (Month)

In [ ]:
import pandas_datareader.data as web
import datetime
import plotly.express as px

start = datetime.datetime(2022, 1, 1)
RDILessGovTransf = web.DataReader('W875RX1', 'fred', start)

# Calcula a variação percentual mensal usando a fórmula especificada
RDILessGovTransf['Variacao_Percentual'] = (RDILessGovTransf['W875RX1'] / RDILessGovTransf['W875RX1'].shift(1)) - 1

# Formata a coluna 'Variacao_Percentual' como porcentagem
RDILessGovTransf['Variacao_Percentual'] = RDILessGovTransf['Variacao_Percentual'] * 100

# Cria uma coluna 'text' com os valores para exibir nas barras, formatados como porcentagem
RDILessGovTransf['text'] = RDILessGovTransf['Variacao_Percentual'].apply(lambda x: '{:.2f}%'.format(x))

# Cria o gráfico de barras
fig = px.bar(RDILessGovTransf,
             x=RDILessGovTransf.index,
             y='Variacao_Percentual',  # Usa a coluna 'Variacao_Percentual' para o eixo y
             title='Real Disposable Income Less Gov. Transfers MoM',
             text='text')

# Configura a aparência do texto nas barras
fig.update_traces(textfont_size=12,
                  textangle=0,
                  textposition="outside",
                  cliponaxis=False)

# Configura os títulos dos eixos
fig.update_layout(yaxis_title='Variação Percentual (%)',
                  xaxis_title='Data')

# Exibe o gráfico
fig.show()

### Labor Force Participation Rate

In [ ]:
import pandas_datareader.data as web
import datetime
import plotly.express as px

start = datetime.datetime(2007, 1, 1)  # Define a data de início como 2007-01-01
LaborForceParticipationRate = web.DataReader('CIVPART', 'fred', start)  # Coleta os dados desde 2007
px.line(LaborForceParticipationRate, x=LaborForceParticipationRate.index, y='CIVPART', title='Labor Force Participation Rate')  # Plota o gráfico

### Average Weeks Unemployed

In [ ]:
import pandas_datareader.data as web
import datetime
import plotly.express as px

start = datetime.datetime(2000, 1, 1)
AverageWeeksUnemployed = web.DataReader('UEMPMEAN', 'fred', start)
px.line(AverageWeeksUnemployed, x=AverageWeeksUnemployed.index, y='UEMPMEAN', title='Average Weeks Unemployed')  # Plota o gráfico

### Average Weeks Unemployed e Média 3M

In [ ]:
import pandas_datareader.data as web
import datetime
import plotly.graph_objects as go

start = datetime.datetime(2010, 1, 1)
AverageWeeksUnemployed = web.DataReader('UEMPMEAN', 'fred', start)

AverageWeeksUnemployed['3m_Avg'] = AverageWeeksUnemployed['UEMPMEAN'].rolling(window=3).mean()

fig = go.Figure()
fig.add_trace(go.Scatter(x=AverageWeeksUnemployed.index, y=AverageWeeksUnemployed['UEMPMEAN'], name='AverageWeeksUnemployed', line=dict(color='blue')))
fig.add_trace(go.Scatter(x=AverageWeeksUnemployed.index, y=AverageWeeksUnemployed['3m_Avg'], name='3m Avg', line=dict(color='darkorange')))
fig.update_layout(title='Average Weeks Unemployed e Média de 3 Meses',
                  yaxis_title='Semanas', xaxis_title='Data')
fig.show()

### Average Hourly Earnings

In [ ]:
import pandas_datareader.data as web
import datetime
import plotly.express as px

start = datetime.datetime(2012, 1, 1)
AverageHourlyEarnings = web.DataReader('CES0500000003', 'fred', start)
px.line(AverageHourlyEarnings, x=AverageHourlyEarnings.index, y='CES0500000003', title='Average Hourly Earnings')  # Plota o gráfico

### Wage Growth Tracker

In [ ]:
import pandas_datareader.data as web
import datetime
import plotly.express as px

start = datetime.datetime(2012, 1, 1)
WageGrowthTracker = web.DataReader('FRBATLWGT3MMAUMHWGO', 'fred', start)
px.line(WageGrowthTracker, x=WageGrowthTracker.index, y='FRBATLWGT3MMAUMHWGO', title='Wage Growth Tracker')  # Plota o gráfico

### Average Hourly Earnings e Wage Growth Tracker (YOY) e Average Hourly Earnings e Wage Growth Tracker (YoY)

In [ ]:
import pandas_datareader.data as web
import datetime
import plotly.graph_objects as go

start = datetime.datetime(2012, 1, 1)
AverageHourlyEarnings = web.DataReader('CES0500000003', 'fred', start)
WageGrowthTracker = web.DataReader('FRBATLWGT3MMAUMHWGO', 'fred', start)

AverageHourlyEarnings['YoY_Change'] = AverageHourlyEarnings['CES0500000003'].pct_change(periods=12) * 100

fig = go.Figure()
fig.add_trace(go.Scatter(x=AverageHourlyEarnings.index, y=AverageHourlyEarnings['YoY_Change'], name='AverageHourlyEarnings YoY', line=dict(color='blue')))
fig.add_trace(go.Scatter(x=WageGrowthTracker.index, y=WageGrowthTracker['FRBATLWGT3MMAUMHWGO'], name='WageGrowthTracker', line=dict(color='darkorange')))
fig.update_layout(title='Average Hourly Earnings YoY e Wage Growth Tracker',
                  yaxis_title='Variação Percentual Anual (%)', xaxis_title='Data')
fig.show()

### Average Hourly Earnings (MoM) e Wage Growth Tracker (3m)

# <span style="color: gray;">**INFLAÇÃO**</span>

### CPI

In [ ]:
# Multiple series:
cpi = web.DataReader('CPIAUCSL', 'fred', start)

In [ ]:
cpi

            CPIAUCSL
DATE
2020-01-01   259.127
2020-02-01   259.250
2020-03-01   258.076
2020-04-01   256.032
2020-05-01   255.802
...              ...
2024-09-01   314.851
2024-10-01   315.564
2024-11-01   316.449
2024-12-01   317.603
2025-01-01   319.086

[61 rows x 1 columns]

In [ ]:
px.line(cpi, x=cpi.index, y='CPIAUCSL')

### Core CPI (Core Consumer Price Index - US)

In [ ]:
CoreCPI = web.DataReader('CPILFESL', 'fred', start)

In [ ]:
CoreCPI

            CPILFESL
DATE
2020-01-01   266.716
2020-02-01   267.370
2020-03-01   267.054
2020-04-01   265.746
2020-05-01   265.412
...              ...
2024-09-01   320.835
2024-10-01   321.688
2024-11-01   322.619
2024-12-01   323.296
2025-01-01   324.739

[61 rows x 1 columns]

In [ ]:
px.line(CoreCPI, x=CoreCPI.index, y='CPILFESL')

### Durable Goods CPI

In [ ]:
DurableGoods = web.DataReader('CUSR0000SAD', 'fred', start)

In [ ]:
DurableGoods

            CUSR0000SAD
DATE
2015-01-01      108.977
2015-02-01      109.185
2015-03-01      109.316
2015-04-01      109.477
2015-05-01      109.465
...                 ...
2024-09-01      122.119
2024-10-01      122.330
2024-11-01      122.563
2024-12-01      122.394
2025-01-01      122.852

[121 rows x 1 columns]

In [ ]:
px.line(DurableGoods, x=DurableGoods.index, y='CUSR0000SAD')

### SERVICES CPI - US

In [ ]:
Services = web.DataReader('CUSR0000SAS', 'fred', start)

In [ ]:
Services

            CUSR0000SAS
DATE
2015-01-01      288.584
2015-02-01      288.949
2015-03-01      289.470
2015-04-01      290.183
2015-05-01      290.543
...                 ...
2024-09-01      406.464
2024-10-01      407.912
2024-11-01      409.020
2024-12-01      410.191
2025-01-01      412.259

[121 rows x 1 columns]

In [ ]:
px.line(Services, x=Services.index, y='CUSR0000SAS')

### CORE SERVICES CPI

In [ ]:
CoreServices = web.DataReader('CUSR0000SASLE', 'fred', start)

In [ ]:
CoreServices

            CUSR0000SASLE
DATE
2020-01-01        343.272
2020-02-01        344.125
2020-03-01        343.768
2020-04-01        342.508
2020-05-01        342.329
...                   ...
2024-09-01        420.479
2024-10-01        421.899
2024-11-01        423.119
2024-12-01        424.231
2025-01-01        426.412

[61 rows x 1 columns]

In [ ]:
px.line(CoreServices, x=CoreServices.index, y='CUSR0000SASLE')

### CPI and Core CPI (YoY Comparison)

In [ ]:
import pandas_datareader.data as web
import datetime
import plotly.express as px

start = datetime.datetime(2000, 1, 1)
end = datetime.datetime.now()

cpi = web.DataReader('CPIAUCSL', 'fred', start, end)
core_cpi = web.DataReader('CPILFESL', 'fred', start, end)

# Calculate YoY percentage change
cpi['YoY_Change'] = cpi['CPIAUCSL'].pct_change(periods=12) * 100
core_cpi['YoY_Change'] = core_cpi['CPILFESL'].pct_change(periods=12) * 100

# Combine data for plotting
yoy_data = cpi[['YoY_Change']].rename(columns={'YoY_Change': 'CPI'})
yoy_data['Core CPI'] = core_cpi['YoY_Change']

# Create the chart with specified colors
fig = px.line(yoy_data,
              x=yoy_data.index,
              y=['CPI', 'Core CPI'],
              title='CPI and Core CPI YoY Comparison',
              color_discrete_map={'CPI': 'blue', 'Core CPI': 'darkorange'})

# Add a dotted line at 2%
fig.add_shape(type='line',
              x0=yoy_data.index.min(),
              y0=2,
              x1=yoy_data.index.max(),
              y1=2,
              line=dict(color='black', dash='dot'))

# Add a solid line at 0%
fig.add_shape(type='line',
              x0=yoy_data.index.min(),
              y0=0,
              x1=yoy_data.index.max(),
              y1=0,
              line=dict(color='black'))

fig.update_layout(yaxis_title='YoY Percentage Change (%)',
                  xaxis_title='Date')
fig.show()

### CPI E Core CPI (Variação Mensal)

In [ ]:
#CPI E CORE CPI (VARIAÇÃO MENSAL)
import pandas_datareader.data as web
import datetime
import plotly.express as px
import pandas as pd

# Definir a data de início e fim
start = datetime.datetime(2023, 1, 1)
end = datetime.datetime(2025, 12, 31)

# Coletar dados do CPI e Core CPI dentro do período especificado
cpi = web.DataReader('CPIAUCSL', 'fred', start, end)
corecpi = web.DataReader('CPILFESL', 'fred', start, end)  # Usando CPILFESL para Core CPI

# Calcular a variação percentual
cpi_percentual = cpi.pct_change()*100
corecpi_percentual = corecpi.pct_change()*100

# Juntar os dados em um único DataFrame para o gráfico
dados_grafico = pd.concat([cpi_percentual.rename(columns={'CPIAUCSL': 'CPI'}),
                           corecpi_percentual.rename(columns={'CPILFESL': 'CoreCPI'})], axis=1)

# Arredondar os valores para duas casas decimais
dados_grafico['CPI'] = dados_grafico['CPI'].round(2)
dados_grafico['CoreCPI'] = dados_grafico['CoreCPI'].round(2)

# Criar o gráfico com Plotly Express
fig = px.bar(dados_grafico,
             x=dados_grafico.index,
             y=['CPI', 'CoreCPI'],
             barmode='group',
             labels={'value': 'Variação Percentual (%)', 'variable': 'Índice'},
             text_auto=True,  # Exibir os valores arredondados
             color_discrete_map={'CPI': 'blue', 'CoreCPI': 'darkorange'},
             title="CPI e Core CPI (Variação Mensal)")  # Adiciona o título

# Formatar o eixo x para mostrar ano e mês
fig.update_xaxes(
    tickformat="%Y-%m",  # Formato para ano e mês (YYYY-MM)
    dtick="M1",          # Intervalo de ticks mensal
    title_text="Data (Ano-Mês)"  # Título do eixo x
)

# Ajustar a posição e o tamanho da fonte dos números acima das barras
fig.update_traces(textposition='outside', textfont_size=25)

# Personalizar o formato do texto para incluir o símbolo de porcentagem
fig.update_traces(texttemplate='%{y:.2f}%')

# Exibir o gráfico
fig.show()

### Core CPI (3M E 6M Annualized)

In [ ]:
import pandas_datareader.data as web
import datetime
import plotly.express as px

# ... (código anterior para coletar e preparar dados) ...

# Cria o gráfico com cores especificadas
fig = px.line(core_cpi,
              x=core_cpi.index,
              y=['3-Month_Annualized', '6-Month_Annualized'],
              title='Core CPI Anualizado em 3 e 6 Meses',
              color_discrete_map={'3-Month_Annualized': 'blue', '6-Month_Annualized': 'darkorange'})

# Adiciona uma linha sólida em 0%
fig.add_shape(type='line',
              x0=core_cpi.index.min(),
              y0=0,
              x1=core_cpi.index.max(),
              y1=0,
              line=dict(color='black'))

# Adiciona uma linha pontilhada preta em 0.02
fig.add_shape(type='line',
              x0=core_cpi.index.min(),
              y0=0.02,
              x1=core_cpi.index.max(),
              y1=0.02,
              line=dict(color='black', dash='dot'))  # dash='dot' cria a linha pontilhada


fig.update_layout(yaxis_title='Variação Percentual Anualizada (%)',
                  xaxis_title='Data',
                 legend_title_text='')  # Remove o título da legenda

fig.show()

### Durable Goods e Services CPI (YoY)

In [ ]:
import pandas_datareader.data as web
import datetime
import plotly.express as px

start = datetime.datetime(2000, 1, 1)
end = datetime.datetime.now()

durable_goods = web.DataReader('CUSR0000SAD', 'fred', start, end)
services = web.DataReader('CUSR0000SAS', 'fred', start, end)

# Calcula a variação percentual YoY
durable_goods['YoY_Change'] = durable_goods['CUSR0000SAD'].pct_change(periods=12) * 100
services['YoY_Change'] = services['CUSR0000SAS'].pct_change(periods=12) * 100

# Combina os dados para plotagem
yoy_data = durable_goods[['YoY_Change']].rename(columns={'YoY_Change': 'Durable Goods'})
yoy_data['Services'] = services['YoY_Change']

# Cria o gráfico com cores especificadas
fig = px.line(yoy_data,
              x=yoy_data.index,
              y=['Durable Goods', 'Services'],
              title='Durable Goods e Services YoY',
              color_discrete_map={'Durable Goods': 'blue', 'Services': 'darkorange'})

# Adiciona uma linha sólida em 0%
fig.add_shape(type='line',
              x0=yoy_data.index.min(),
              y0=0,
              x1=yoy_data.index.max(),
              y1=0,
              line=dict(color='black'))

fig.update_layout(yaxis_title='Variação Percentual Anual (%)',
                  xaxis_title='Data', legend_title_text='')

fig.show()

### Durable Goods e Services CPI (Month)

In [ ]:
import pandas_datareader.data as web
import datetime
import plotly.express as px
import pandas as pd

# Definir a data de início e fim
start = datetime.datetime(2023, 1, 1)  # Você pode ajustar a data de início aqui
end = datetime.datetime.now()

# Coletar dados do Durable Goods e Services dentro do período especificado
durable_goods = web.DataReader('CUSR0000SAD', 'fred', start, end)
services = web.DataReader('CUSR0000SAS', 'fred', start, end)

# Calcular a variação percentual mensal
durable_goods_percentual = durable_goods.pct_change() * 100
services_percentual = services.pct_change() * 100

# Juntar os dados em um único DataFrame para o gráfico
dados_grafico = pd.concat([durable_goods_percentual.rename(columns={'CUSR0000SAD': 'Durable Goods'}),
                           services_percentual.rename(columns={'CUSR0000SAS': 'Services'})], axis=1)

# Arredondar os valores para duas casas decimais
dados_grafico['Durable Goods'] = dados_grafico['Durable Goods'].round(2)
dados_grafico['Services'] = dados_grafico['Services'].round(2)

# Criar o gráfico com Plotly Express
fig = px.bar(dados_grafico,
             x=dados_grafico.index,
             y=['Durable Goods', 'Services'],
             barmode='group',
             labels={'value': 'Variação Percentual (%)', 'variable': 'Índice'},
             text_auto=True,  # Exibir os valores arredondados
             color_discrete_map={'Durable Goods': 'blue', 'Services': 'darkorange'},
             title="Durable Goods e Services (Variação Mensal)")

# Formatar o eixo x para mostrar ano e mês
fig.update_xaxes(
    tickformat="%Y-%m",  # Formato para ano e mês (YYYY-MM)
    dtick="M1",          # Intervalo de ticks mensal
    title_text="Data (Ano-Mês)"  # Título do eixo x
)

# Ajustar a posição e o tamanho da fonte dos números acima das barras
fig.update_traces(textposition='outside', textfont_size=10)

# Personalizar o formato do texto para incluir o símbolo de porcentagem
fig.update_traces(texttemplate='%{y:.2f}%')

# Exibir o gráfico
fig.show()

### PCE

In [ ]:
PCE = web.DataReader('PCEPI', 'fred', start)

In [ ]:
PCE

              PCEPI
DATE
2023-01-01  119.007
2023-02-01  119.401
2023-03-01  119.553
2023-04-01  119.970
2023-05-01  120.140
2023-06-01  120.435
2023-07-01  120.598
2023-08-01  120.965
2023-09-01  121.387
2023-10-01  121.421
2023-11-01  121.415
2023-12-01  121.602
2024-01-01  122.115
2024-02-01  122.494
2024-03-01  122.912
2024-04-01  123.234
2024-05-01  123.224
2024-06-01  123.369
2024-07-01  123.575
2024-08-01  123.727
2024-09-01  123.939
2024-10-01  124.235
2024-11-01  124.387
2024-12-01  124.705

In [ ]:
px.line(PCE, x=PCE.index, y='PCEPI')

### Core-PCE

In [ ]:
COREPCE = web.DataReader('PCEPILFE', 'fred', start)

In [ ]:
COREPCE

            PCEPILFE
DATE
2023-01-01   117.526
2023-02-01   117.963
2023-03-01   118.304
2023-04-01   118.715
2023-05-01   119.063
2023-06-01   119.370
2023-07-01   119.536
2023-08-01   119.658
2023-09-01   120.040
2023-10-01   120.200
2023-11-01   120.309
2023-12-01   120.528
2024-01-01   121.128
2024-02-01   121.418
2024-03-01   121.829
2024-04-01   122.140
2024-05-01   122.239
2024-06-01   122.510
2024-07-01   122.722
2024-08-01   122.926
2024-09-01   123.234
2024-10-01   123.570
2024-11-01   123.703
2024-12-01   123.896

In [ ]:
px.line(COREPCE, x=COREPCE.index, y='PCEPILFE')

### Durable Goods PCE

In [ ]:
DURABLEPCE = web.DataReader('DGDSRG3M086SBEA', 'fred', start)

In [ ]:
DURABLEPCE

            DGDSRG3M086SBEA
DATE
2023-01-01          114.837
2023-02-01          115.092
2023-03-01          114.910
2023-04-01          115.216
2023-05-01          115.094
2023-06-01          115.023
2023-07-01          114.732
2023-08-01          115.419
2023-09-01          115.622
2023-10-01          115.310
2023-11-01          114.679
2023-12-01          114.430
2024-01-01          114.245
2024-02-01          114.783
2024-03-01          114.950
2024-04-01          115.201
2024-05-01          114.784
2024-06-01          114.587
2024-07-01          114.559
2024-08-01          114.387
2024-09-01          114.248
2024-10-01          114.174
2024-11-01          114.222
2024-12-01          114.410

In [ ]:
px.line(DURABLEPCE, x=DURABLEPCE.index, y='DGDSRG3M086SBEA')

### Services PCE

In [ ]:
SERVICESPCE = web.DataReader('DSERRG3M086SBEA', 'fred', start)

In [ ]:
SERVICESPCE

            DSERRG3M086SBEA
DATE
2023-01-01          120.915
2023-02-01          121.382
2023-03-01          121.707
2023-04-01          122.182
2023-05-01          122.502
2023-06-01          122.985
2023-07-01          123.383
2023-08-01          123.584
2023-09-01          124.120
2023-10-01          124.332
2023-11-01          124.649
2023-12-01          125.060
2024-01-01          125.930
2024-02-01          126.225
2024-03-01          126.771
2024-04-01          127.128
2024-05-01          127.326
2024-06-01          127.646
2024-07-01          127.972
2024-08-01          128.291
2024-09-01          128.682
2024-10-01          129.169
2024-11-01          129.375
2024-12-01          129.760

In [ ]:
px.line(SERVICESPCE, x=SERVICESPCE.index, y='DSERRG3M086SBEA')

### PCE E Core PCE (YoY Comparison)

In [ ]:
import pandas_datareader.data as web
import datetime
import plotly.express as px

start = datetime.datetime(2000, 1, 1)
end = datetime.datetime.now()

pce = web.DataReader('PCEPI', 'fred', start, end)
core_pce = web.DataReader('PCEPILFE', 'fred', start, end)

# Calculate YoY percentage change
pce['YoY_Change'] = pce['PCEPI'].pct_change(periods=12) * 100
core_pce['YoY_Change'] = core_pce['PCEPILFE'].pct_change(periods=12) * 100

# Combine data for plotting
yoy_data = pce[['YoY_Change']].rename(columns={'YoY_Change': 'PCE'})
yoy_data['Core PCE'] = core_pce['YoY_Change']

# Create the chart with specified colors
fig = px.line(yoy_data,
              x=yoy_data.index,
              y=['PCE', 'Core PCE'],
              title='PCE and Core PCE YoY Comparison',
              color_discrete_map={'PCE': 'blue', 'Core PCE': 'darkorange'})  # Add color mapping

# Add a dotted line at 2%
fig.add_shape(type='line',
              x0=yoy_data.index.min(),
              y0=2,
              x1=yoy_data.index.max(),
              y1=2,
              line=dict(color='black', dash='dot'))

# Add a solid line at 0%
fig.add_shape(type='line',
              x0=yoy_data.index.min(),
              y0=0,
              x1=yoy_data.index.max(),
              y1=0,
              line=dict(color='black'))  # Default line is solid

fig.update_layout(yaxis_title='YoY Percentage Change (%)',
                  xaxis_title='Date')
fig.show()

### PCE E Core PCE (Variação Mensal)

In [ ]:
#PCE E CORE PCE (VARIAÇÃO MENSAL)
import pandas_datareader.data as web
import datetime
import plotly.express as px
import pandas as pd

# Definir a data de início e fim
start = datetime.datetime(2023, 1, 1)
end = datetime.datetime(2025, 12, 31)

# Coletar dados do PCE e Core PCE dentro do período especificado
pce = web.DataReader('PCEPI', 'fred', start, end)
corepce = web.DataReader('PCEPILFE', 'fred', start, end)

# Calcular a variação percentual
pce_percentual = pce.pct_change()*100
corepce_percentual = corepce.pct_change()*100

# Juntar os dados em um único DataFrame para o gráfico
dados_grafico = pd.concat([pce_percentual.rename(columns={'PCEPI': 'PCE'}),
                           corepce_percentual.rename(columns={'PCEPILFE': 'CorePCE'})], axis=1)

# Arredondar os valores para duas casas decimais
dados_grafico['PCE'] = dados_grafico['PCE'].round(2)
dados_grafico['CorePCE'] = dados_grafico['CorePCE'].round(2)

# Criar o gráfico com Plotly Express
fig = px.bar(dados_grafico,
             x=dados_grafico.index,
             y=['PCE', 'CorePCE'],
             barmode='group',
             labels={'value': 'Variação Percentual (%)', 'variable': 'Índice'},
             text_auto=True,  # Exibir os valores arredondados
             color_discrete_map={'PCE': 'blue', 'CorePCE': 'darkorange'},  # Define as cores
             title="PCE e Core PCE (Variação Mensal)")  # Adiciona o título

# Formatar o eixo x para mostrar ano e mês
fig.update_xaxes(
    tickformat="%Y-%m",  # Formato para ano e mês (YYYY-MM)
    dtick="M1",          # Intervalo de ticks mensal
    title_text="Data (Ano-Mês)"  # Título do eixo x
)

# Ajustar a posição e o tamanho da fonte dos números acima das barras
fig.update_traces(textposition='outside', textfont_size=25)

# Personalizar o formato do texto para incluir o símbolo de porcentagem
fig.update_traces(texttemplate='%{y:.2f}%')

# Exibir o gráfico
fig.show()

### Core PCE (3M E 6M Annualized)

In [ ]:
import pandas_datareader.data as web
import datetime
import plotly.express as px

start = datetime.datetime(2015, 1, 1)
end = datetime.datetime.now()

core_pce = web.DataReader('PCEPILFE', 'fred', start, end)

# Calcula a variação percentual
core_pce['3-Month_Change'] = core_pce['PCEPILFE'].pct_change(periods=3)
core_pce['6-Month_Change'] = core_pce['PCEPILFE'].pct_change(periods=6)

# Anualiza a variação percentual
core_pce['3-Month_Annualized'] = (1 + core_pce['3-Month_Change']) ** (12 / 3) - 1
core_pce['6-Month_Annualized'] = (1 + core_pce['6-Month_Change']) ** (12 / 6) - 1


# Cria o gráfico com cores especificadas
fig = px.line(core_pce,
              x=core_pce.index,
              y=['3-Month_Annualized', '6-Month_Annualized'],
              title='Core PCE Anualizado em 3 e 6 Meses',
              color_discrete_map={'3-Month_Annualized': 'blue', '6-Month_Annualized': 'darkorange'})

# Adiciona uma linha sólida em 0%
fig.add_shape(type='line',
              x0=core_pce.index.min(),
              y0=0,
              x1=core_pce.index.max(),
              y1=0,
              line=dict(color='black'))

# Adiciona uma linha pontilhada preta em 0.02
fig.add_shape(type='line',
              x0=core_pce.index.min(),
              y0=0.02,
              x1=core_pce.index.max(),
              y1=0.02,
              line=dict(color='black', dash='dot'))  # dash='dot' cria a linha pontilhada


fig.update_layout(yaxis_title='Variação Percentual Anualizada (%)',
                  xaxis_title='Data',
                 legend_title_text='')  # Remove o título da legenda

fig.show()

### Durable Goods E Services PCE (YoY)

In [ ]:
import pandas_datareader.data as web
import datetime
import plotly.express as px

# ... (código anterior para coletar e preparar dados) ...

# Cria o gráfico com cores especificadas
fig = px.line(yoy_data,
              x=yoy_data.index,
              y=['Durable PCE', 'Services PCE'],
              title='Durable PCE e Services PCE YoY Comparison',
              color_discrete_map={'Durable PCE': 'blue', 'Services PCE': 'darkorange'})

# Adiciona uma linha sólida em 0%
fig.add_shape(type='line',
              x0=yoy_data.index.min(),
              y0=0,
              x1=yoy_data.index.max(),
              y1=0,
              line=dict(color='black'))

# Adiciona uma linha pontilhada preta em 2%
fig.add_shape(type='line',
              x0=yoy_data.index.min(),
              y0=2,  # Define a posição y da linha
              x1=yoy_data.index.max(),
              y1=2,  # Define a posição y da linha
              line=dict(color='black', dash='dot'))  # dash='dot' cria a linha pontilhada

fig.update_layout(yaxis_title='YoY Percentage Change (%)',
                  xaxis_title='Date', legend_title_text='')

fig.show()

### Durable Goods e Services PCE (Month)

In [ ]:
import pandas_datareader.data as web
import datetime
import plotly.express as px
import pandas as pd

# Definir a data de início e fim
start = datetime.datetime(2023, 1, 1)  # Você pode ajustar a data de início aqui
end = datetime.datetime.now()

# Coletar dados do Durable PCE e Services PCE dentro do período especificado
durable_pce = web.DataReader('DGDSRG3M086SBEA', 'fred', start, end)
services_pce = web.DataReader('DSERRG3M086SBEA', 'fred', start, end)

# Calcular a variação percentual mensal
durable_pce_percentual = durable_pce.pct_change() * 100
services_pce_percentual = services_pce.pct_change() * 100

# Juntar os dados em um único DataFrame para o gráfico
dados_grafico = pd.concat([durable_pce_percentual.rename(columns={'DGDSRG3M086SBEA': 'Durable PCE'}),
                           services_pce_percentual.rename(columns={'DSERRG3M086SBEA': 'Services PCE'})], axis=1)

# Arredondar os valores para duas casas decimais
dados_grafico['Durable PCE'] = dados_grafico['Durable PCE'].round(2)
dados_grafico['Services PCE'] = dados_grafico['Services PCE'].round(2)

# Criar o gráfico com Plotly Express
fig = px.bar(dados_grafico,
             x=dados_grafico.index,
             y=['Durable PCE', 'Services PCE'],
             barmode='group',
             labels={'value': 'Variação Percentual (%)', 'variable': 'Índice'},
             text_auto=True,  # Exibir os valores arredondados
             color_discrete_map={'Durable PCE': 'blue', 'Services PCE': 'darkorange'},
             title="Durable PCE e Services PCE (Variação Mensal)")

# Formatar o eixo x para mostrar ano e mês
fig.update_xaxes(
    tickformat="%Y-%m",  # Formato para ano e mês (YYYY-MM)
    dtick="M1",          # Intervalo de ticks mensal
    title_text="Data (Ano-Mês)"  # Título do eixo x
)

# Ajustar a posição e o tamanho da fonte dos números acima das barras
fig.update_traces(textposition='outside', textfont_size=10)

# Personalizar o formato do texto para incluir o símbolo de porcentagem
fig.update_traces(texttemplate='%{y:.2f}%')

# Exibir o gráfico
fig.show()

### Producer Price Index (PPI - US)

In [ ]:
PPI = web.DataReader('PPIFIS', 'fred', start)

In [ ]:
PPI

             PPIFIS
DATE
2020-01-01  119.200
2020-02-01  118.600
2020-03-01  118.000
2020-04-01  116.600
2020-05-01  117.200
...             ...
2024-09-01  145.792
2024-10-01  146.055
2024-11-01  146.397
2024-12-01  147.127
2025-01-01  147.716

[61 rows x 1 columns]

In [ ]:
px.line(PPI, x=PPI.index, y='PPIFIS')

### Core Producer Price Index (Core PPI - US)

In [ ]:
COREPPI = web.DataReader('WPSFD49116', 'fred', start)

In [ ]:
COREPPI

            WPSFD49116
DATE
2020-01-01     111.500
2020-02-01     111.400
2020-03-01     111.200
2020-04-01     110.300
2020-05-01     110.400
...                ...
2024-09-01     133.257
2024-10-01     133.604
2024-11-01     133.789
2024-12-01     134.262
2025-01-01     134.694

[61 rows x 1 columns]

In [ ]:
px.line(COREPPI, x=COREPPI.index, y='WPSFD49116')

### PPI E Core PPI (Annual)

In [ ]:
import pandas_datareader.data as web
import datetime
import plotly.express as px

# ... (código anterior para coletar e preparar dados) ...

# Cria o gráfico com cores especificadas
fig = px.line(yoy_data,
              x=yoy_data.index,
              y=['PPI', 'Core PPI'],
              title='Annual PPI e Annual CorePPI',
              color_discrete_map={'PPI': 'blue', 'Core PPI': 'darkorange'})

# Remove a linha pontilhada em 2.0 (comente ou remova esta parte)
# fig.add_shape(type='line',
#               x0=yoy_data.index.min(),
#               y0=2,
#               x1=yoy_data.index.max(),
#               y1=2,
#               line=dict(color='black', dash='dot'))


# Adiciona uma linha sólida em 0%
fig.add_shape(type='line',
              x0=yoy_data.index.min(),
              y0=0,
              x1=yoy_data.index.max(),
              y1=0,
              line=dict(color='black'))

fig.update_layout(yaxis_title='Variação Percentual Anual (%)',
                  xaxis_title='Data')
fig.show()

### PPI E Core PPI (Variação Mensal)

In [ ]:
#PPI and Core PPI (Monthly Percentage Change) Bar Chart
import pandas_datareader.data as web
import datetime
import plotly.express as px
import pandas as pd

# Definir a data de início e fim
start = datetime.datetime(2023, 1, 1)
end = datetime.datetime(2025, 12, 31)

# Coletar dados do PPI e Core PPI dentro do período especificado
ppi = web.DataReader('PPIFIS', 'fred', start, end)
coreppi = web.DataReader('WPSFD49116', 'fred', start, end)

# Calcular a variação percentual
ppi_percentual = ppi.pct_change()*100
coreppi_percentual = coreppi.pct_change()*100

# Juntar os dados em um único DataFrame para o gráfico
dados_grafico = pd.concat([ppi_percentual.rename(columns={'PPIFIS': 'PPI'}),
                           coreppi_percentual.rename(columns={'WPSFD49116': 'CorePPI'})], axis=1)

# Arredondar os valores para duas casas decimais
dados_grafico['PPI'] = dados_grafico['PPI'].round(2)
dados_grafico['CorePPI'] = dados_grafico['CorePPI'].round(2)

# Criar o gráfico com Plotly Express
fig = px.bar(dados_grafico,
             x=dados_grafico.index,
             y=['PPI', 'CorePPI'],
             barmode='group',
             labels={'value': 'Variação Percentual (%)', 'variable': 'Índice'},
             text_auto=True,  # Exibir os valores arredondados
             color_discrete_map={'PPI': 'blue', 'CorePPI': 'darkorange'},
             title="PPI e CorePPI (Variação Mensal)")  # Adiciona o título

# Formatar o eixo x para mostrar ano e mês
fig.update_xaxes(
    tickformat="%Y-%m",  # Formato para ano e mês (YYYY-MM)
    dtick="M1",          # Intervalo de ticks mensal
    title_text="Data (Ano-Mês)"  # Título do eixo x
)

# Ajustar a posição e o tamanho da fonte dos números acima das barras
fig.update_traces(textposition='outside', textfont_size=25)

# Personalizar o formato do texto para incluir o símbolo de porcentagem
fig.update_traces(texttemplate='%{y:.2f}%')

# Exibir o gráfico
fig.show()

### Expectativa Inflação 1 ano

In [ ]:
EXPECTATIONSINFLATION = web.DataReader('MICH', 'fred', start)

In [ ]:
EXPECTATIONSINFLATION

            MICH
DATE
2023-01-01   3.9
2023-02-01   4.2
2023-03-01   3.6
2023-04-01   4.7
2023-05-01   4.2
2023-06-01   3.3
2023-07-01   3.4
2023-08-01   3.5
2023-09-01   3.2
2023-10-01   4.2
2023-11-01   4.5
2023-12-01   3.1
2024-01-01   2.9
2024-02-01   3.0
2024-03-01   2.9
2024-04-01   3.2
2024-05-01   3.3
2024-06-01   3.0
2024-07-01   2.9
2024-08-01   2.8
2024-09-01   2.7
2024-10-01   2.7
2024-11-01   2.6
2024-12-01   2.8

In [ ]:
fig = px.line(filtered_data, x=filtered_data.index, y='MICH')

# Add the horizontal line with a name
fig.add_shape(
    type='line',
    x0=filtered_data.index.min(),
    y0=3.11,
    x1=filtered_data.index.max(),
    y1=3.11,
    line=dict(color='black', dash='dot'),
    name='Expectativa da Inflação Média'  # Set the name for the legend
)

# Format x-axis to show year and month
fig.update_xaxes(
    tickformat="%Y-%m",  # Format string for year and month
    dtick="M1",          # Show ticks for each month
    title_text="Data"   # Set x-axis title (optional)
)

# Show the legend
fig.update_layout(showlegend=True, title_text="Expectativa da Inflação 1 Ano e Média de 3.11(Expec. Entrevistados)")

fig.show()

### Gráfico Inflação

In [ ]:
px.bar(data_frame=cpi.pct_change()*100, x=cpi.index, y='CPIAUCSL', labels={'CPIAUCSL':'Inflação (%)'})

# <span style="color: gray;">**MONETARY** **POLICE** + **MARKET**</span>

### Fed Funds Rate (FFR)

In [ ]:
import pandas_datareader.data as web
import datetime
import plotly.express as px

start = datetime.datetime(2000, 1, 1)
FFR = web.DataReader('DFF', 'fred', start)
px.line(FFR, x=FFR.index, y='DFF', title='Fed Funds Rate (FFR)')  # Plota o gráfico

In [ ]:
FFR

             DFF
DATE
2020-01-01  1.55
2020-01-02  1.55
2020-01-03  1.55
2020-01-04  1.55
2020-01-05  1.55
...          ...
2025-02-08  4.33
2025-02-09  4.33
2025-02-10  4.33
2025-02-11  4.33
2025-02-12  4.33

[1870 rows x 1 columns]

### 30Y Mortgage Rate

In [ ]:
Mortgage = web.DataReader('MORTGAGE30US', 'fred', start)

In [ ]:
Mortgage

            MORTGAGE30US
DATE
2000-01-07          8.15
2000-01-14          8.18
2000-01-21          8.26
2000-01-28          8.25
2000-02-04          8.25
...                  ...
2025-01-16          7.04
2025-01-23          6.96
2025-01-30          6.95
2025-02-06          6.89
2025-02-13          6.87

[1311 rows x 1 columns]

In [ ]:
px.line(Mortgage, x=Mortgage.index, y='MORTGAGE30US')

### St.Louis Fed Financial Stress Index

In [ ]:
import pandas_datareader.data as web
import datetime
import plotly.express as px

start = datetime.datetime(2000, 1, 1)
Stress = web.DataReader('STLFSI4', 'fred', start)
px.line(Stress, x=Stress.index, y='STLFSI4', title='St.Louis Fed Financial Stress Index')  # Plota o gráfico

In [ ]:
Stress

            STLFSI4
DATE
2020-01-03  -0.2461
2020-01-10  -0.3718
2020-01-17  -0.5370
2020-01-24  -0.4239
2020-01-31  -0.1367
...             ...
2025-01-10  -0.8148
2025-01-17  -0.8329
2025-01-24  -0.9768
2025-01-31  -0.7640
2025-02-07  -0.7872

[267 rows x 1 columns]

### Chicago Fed (NFCI)

In [ ]:
ChicagoFed = web.DataReader('NFCI', 'fred', start)

In [ ]:
ChicagoFed

               NFCI
DATE
2020-01-03 -0.56287
2020-01-10 -0.58269
2020-01-17 -0.60385
2020-01-24 -0.62184
2020-01-31 -0.63229
...             ...
2025-01-10 -0.60561
2025-01-17 -0.61772
2025-01-24 -0.62787
2025-01-31 -0.63544
2025-02-07 -0.64001

[267 rows x 1 columns]

In [ ]:
px.line(ChicagoFed, x=ChicagoFed.index, y='NFCI')

### FED Balance Sheet (Assets) e FED Balance Sheet (Assets) YoY

FED Balance Sheet (Assets)

In [ ]:
FEDASSETS = web.DataReader('WALCL', 'fred', start)

In [ ]:
FEDASSETS

              WALCL
DATE
2002-12-18   719542
2002-12-25   732059
2003-01-01   730994
2003-01-08   723762
2003-01-15   720074
...             ...
2025-01-15  6834070
2025-01-22  6831760
2025-01-29  6818186
2025-02-05  6810935
2025-02-12  6813513

[1157 rows x 1 columns]

In [ ]:
# Defina a data de início
start_date = '2003-01-01'

# Filtre o DataFrame para incluir apenas dados a partir da data de início
filtered_data = FEDASSETS[FEDASSETS.index >= pd.to_datetime(start_date)]

# Crie o gráfico de área
fig = px.area(filtered_data, x=filtered_data.index, y='WALCL')
fig.update_traces(line_color='blue', fillcolor='rgba(0, 0, 255, 0.5)')
fig.show()

FED Balance Sheets (Assets) YoY

In [ ]:
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

# Defina a data de início
start_date = '2003-01-01'

# Filtre o DataFrame para incluir apenas dados a partir da data de início
filtered_data = FEDASSETS[FEDASSETS.index >= pd.to_datetime(start_date)]

# Calcular a variação percentual ano a ano (YoY)
filtered_data['WALCL_YoY'] = filtered_data['WALCL'].pct_change(periods=12) * 100

# Crie o gráfico de linha
fig = px.line(filtered_data, x=filtered_data.index, y='WALCL_YoY',
              title='FED ASSETS YoY',
              color_discrete_sequence=['blue'])  # Definir a cor como azul

# Adicionar linha preta no valor 0
fig.add_shape(type='line',
              x0=filtered_data.index.min(), x1=filtered_data.index.max(),
              y0=0, y1=0,
              line=dict(color='black', width=2))

fig.show()

/var/folders/pw/n8qw3q6n66v1gg613kl1wt8w0000gn/T/ipykernel_4891/1907467558.py:12: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

### Monetary Base: Total e Currency Component of M1

Monetary Base Total

In [ ]:
MonetaryBase = web.DataReader('BOGMBASE', 'fred', start)

In [ ]:
MonetaryBase

            BOGMBASE
DATE
2000-01-01     601.9
2000-02-01     578.0
2000-03-01     577.1
2000-04-01     578.6
2000-05-01     580.6
...              ...
2024-08-01    5670.2
2024-09-01    5588.4
2024-10-01    5567.2
2024-11-01    5616.5
2024-12-01    5604.1

[300 rows x 1 columns]

In [ ]:
# Defina a data de início
start_date = '2003-01-01'

# Filtre o DataFrame para incluir apenas dados a partir da data de início
filtered_data = MonetaryBase[MonetaryBase.index >= pd.to_datetime(start_date)]

# Crie o gráfico de área
fig = px.area(filtered_data, x=filtered_data.index, y='BOGMBASE')
fig.update_traces(line_color='blue', fillcolor='rgba(0, 0, 255, 0.5)')
fig.show()

Currency Component of M1

In [ ]:
ComponentM1 = web.DataReader('CURRSL', 'fred', start)

In [ ]:
ComponentM1

            CURRSL
DATE
2000-01-01   524.9
2000-02-01   518.0
2000-03-01   517.0
2000-04-01   517.8
2000-05-01   519.1
...            ...
2024-08-01  2262.6
2024-09-01  2271.4
2024-10-01  2277.5
2024-11-01  2277.8
2024-12-01  2280.2

[300 rows x 1 columns]

In [ ]:
# Defina a data de início
start_date = '2003-01-01'

# Filtre o DataFrame para incluir apenas dados a partir da data de início
filtered_data = ComponentM1[ComponentM1.index >= pd.to_datetime(start_date)]

# Crie o gráfico de área
fig = px.line(filtered_data, x=filtered_data.index, y='CURRSL')
fig.update_traces(line_color='blue', fillcolor='rgba(0, 0, 255, 0.5)')
fig.show()

### US Bank Reserves e US Bank Reserves YoY

US Bank Reserves

In [ ]:
import pandas_datareader.data as web
import datetime
import plotly.express as px

start = datetime.datetime(2000, 1, 1)

# Buscar os dados do FRED
MonetaryBase = web.DataReader('BOGMBASE', 'fred', start)
ComponentM1 = web.DataReader('CURRSL', 'fred', start)

# Criar um DataFrame com a subtração
df = MonetaryBase.copy()
df['Subtracao'] = MonetaryBase['BOGMBASE'] - ComponentM1['CURRSL']

# Plotar o gráfico de área
fig = px.area(df, x=df.index, y='Subtracao',
             title='US BANK RESERVES',
             color_discrete_sequence=['blue'])  # Definir a cor como azul

fig.show()

US BANK RESERVES YOY

In [ ]:
import pandas_datareader.data as web
import datetime
import plotly.express as px
import plotly.graph_objects as go

start = datetime.datetime(2000, 1, 1)

# Buscar os dados do FRED
MonetaryBase = web.DataReader('BOGMBASE', 'fred', start)
ComponentM1 = web.DataReader('CURRSL', 'fred', start)

# Criar um DataFrame com a subtração
df = MonetaryBase.copy()
df['Subtracao'] = MonetaryBase['BOGMBASE'] - ComponentM1['CURRSL']

# Calcular a variação ano a ano (YoY)
df['Subtracao_YoY'] = df['Subtracao'].pct_change(periods=12) * 100

# Plotar o gráfico de linha
fig = px.line(df, x=df.index, y='Subtracao_YoY',
              title='US BANK RESERVES YoY',
              color_discrete_sequence=['blue'])  # Definir a cor como azul

# Adicionar linha preta no valor 0
fig.add_shape(type='line',
              x0=df.index.min(), x1=df.index.max(),
              y0=0, y1=0,
              line=dict(color='black', width=1))

fig.show()

### Treasury General Account (TGA)

Treasury General Account (TGA) - Reservas do Tesouro Americano

In [ ]:
TGA = web.DataReader('WTREGEN', 'fred', start)

In [ ]:
TGA

            WTREGEN
DATE
2000-01-05   20.943
2000-01-12    5.326
2000-01-19    5.390
2000-01-26    7.205
2000-02-02    6.131
...             ...
2025-01-22  677.282
2025-01-29  784.206
2025-02-05  805.593
2025-02-12  828.102
2025-02-19  790.062

[1312 rows x 1 columns]

In [ ]:
# Defina a data de início
start_date = '2003-01-01'

# Filtre o DataFrame para incluir apenas dados a partir da data de início
filtered_data = TGA[TGA.index >= pd.to_datetime(start_date)]

# Crie o gráfico de área
fig = px.area(filtered_data, x=filtered_data.index, y='WTREGEN', title='Treasury General Account (TGA) - Reservas do Tesouro Americano')  # Adicione o título aqui
fig.update_traces(line_color='blue', fillcolor='rgba(0, 0, 255, 0.5)')
fig.show()

### Personal Savings Rate

In [ ]:
Savings = web.DataReader('PSAVERT', 'fred', start)

In [ ]:
Savings

            PSAVERT
DATE
2020-01-01      7.0
2020-02-01      7.5
2020-03-01     12.4
2020-04-01     32.0
2020-05-01     22.8
2020-06-01     18.4
2020-07-01     17.8
2020-08-01     13.9
2020-09-01     13.1
2020-10-01     12.6
2020-11-01     11.8
2020-12-01     11.8
2021-01-01     19.2
2021-02-01     12.6
2021-03-01     25.9
2021-04-01     12.0
2021-05-01      9.6
2021-06-01      8.4
2021-07-01      9.2
2021-08-01      8.4
2021-09-01      7.2
2021-10-01      6.6
2021-11-01      6.1
2021-12-01      6.0
2022-01-01      3.6
2022-02-01      3.6
2022-03-01      2.7
2022-04-01      2.2
2022-05-01      2.3
2022-06-01      2.0
2022-07-01      3.1
2022-08-01      3.1
2022-09-01      3.1
2022-10-01      3.2
2022-11-01      3.4
2022-12-01      3.7
2023-01-01      4.2
2023-02-01      4.6
2023-03-01      5.3
2023-04-01      5.0
2023-05-01      5.2
2023-06-01      5.0
2023-07-01      4.6
2023-08-01      4.7
2023-09-01      4.4
2023-10-01      4.5
2023-11-01      4.6
2023-12-01      4.4
2024-01-01      5.5
2024-02-01      5.4
2024-03-01      5.2
2024-04-01      5.1
2024-05-01      4.9
2024-06-01      4.8
2024-07-01      4.4
2024-08-01      4.4
2024-09-01      4.1
2024-10-01      4.3
2024-11-01      4.1
2024-12-01      3.8

In [ ]:
px.line(Savings, x=Savings.index, y='PSAVERT')

### Retail Money Market Funds(Tri)

In [ ]:
RETAILMONEY = web.DataReader('WRMFNS', 'fred', start)

In [ ]:
RETAILMONEY

            WRMFNS
DATE
2020-01-06  1014.3
2020-01-13  1020.6
2020-01-20  1016.1
2020-01-27  1012.0
2020-02-03  1004.3
...            ...
2024-12-09  2041.3
2024-12-16  2040.1
2024-12-23  2044.2
2024-12-30  2060.5
2025-01-06  2082.7

[262 rows x 1 columns]

In [ ]:
px.line(RETAILMONEY, x=RETAILMONEY.index, y='WRMFNS')

# <span style="color: gray;">**GDP** + **ECI** (**Quarter**)</span>

### Real Final Sales to Domestic Purchasers

In [ ]:
REALFINALSALES = web.DataReader('LB0000031Q020SBEA', 'fred', start)

In [ ]:
REALFINALSALES

            LB0000031Q020SBEA
DATE
2020-01-01          17597.011
2020-04-01          16092.150
2020-07-01          17456.134
2020-10-01          17788.461
2021-01-01          18195.118
2021-04-01          18728.500
2021-07-01          18823.113
2021-10-01          19013.672
2022-01-01          19130.261
2022-04-01          19246.360
2022-07-01          19285.772
2022-10-01          19312.465
2023-01-01          19528.812
2023-04-01          19651.480
2023-07-01          19775.636
2023-10-01          19946.362
2024-01-01          20088.133
2024-04-01          20222.897
2024-07-01          20390.738
2024-10-01          20551.868

In [ ]:
px.line(REALFINALSALES, x=REALFINALSALES.index, y='LB0000031Q020SBEA')

### Employment Cost Index (ECI)

In [ ]:
import pandas_datareader.data as web
import datetime
import plotly.express as px

start = datetime.datetime(2000, 1, 1)
EMPLOYMENTCOST = web.DataReader('ECIALLCIV', 'fred', start)
px.line(EMPLOYMENTCOST, x=EMPLOYMENTCOST.index, y='ECIALLCIV', title='Employment Cost Index (ECI)')  # Plota o gráfico

In [ ]:
EMPLOYMENTCOST

            ECIALLCIV
DATE
2020-01-01      140.0
2020-04-01      140.7
2020-07-01      141.3
2020-10-01      142.5
2021-01-01      143.7
2021-04-01      144.7
2021-07-01      146.5
2021-10-01      148.1
2022-01-01      150.1
2022-04-01      152.1
2022-07-01      153.9
2022-10-01      155.6
2023-01-01      157.4
2023-04-01      159.0
2023-07-01      160.6
2023-10-01      162.1
2024-01-01      164.0
2024-04-01      165.5
2024-07-01      166.8
2024-10-01      168.3

### ECI QoQ e AverageQuarterly ECI

In [ ]:
import pandas_datareader.data as web
import datetime
import plotly.express as px
import plotly.graph_objects as go

start = datetime.datetime(2017, 1, 1)
EMPLOYMENTCOST = web.DataReader('ECIALLCIV', 'fred', start)

# Calculate QoQ percentage change
EMPLOYMENTCOST['QoQ_Change'] = EMPLOYMENTCOST['ECIALLCIV'].pct_change() * 100

# Format the percentage change for display
EMPLOYMENTCOST['QoQ_Change_Text'] = EMPLOYMENTCOST['QoQ_Change'].apply(lambda x: f'{x:.2f}%')

# Calculate average quarterly percentage change
average_quarterly_pct_change = EMPLOYMENTCOST['QoQ_Change'].mean()

# Create the bar plot
fig = px.bar(EMPLOYMENTCOST, x=EMPLOYMENTCOST.index, y='QoQ_Change',
             title='Employment Cost Index (ECI) - QoQ Percentage Change',
             text='QoQ_Change_Text',
             color_discrete_sequence=['blue'])

# Add the average quarterly line
fig.add_shape(
    type="line",
    x0=EMPLOYMENTCOST.index.min(),
    y0=average_quarterly_pct_change,
    x1=EMPLOYMENTCOST.index.max(),
    y1=average_quarterly_pct_change,
    line=dict(color="darkorange", width=2),
)

# Customize the layout and text position
fig.update_layout(xaxis_title='Data', yaxis_title='Percentage Change (%)')
fig.update_traces(textposition='outside', selector=dict(type='bar'))  # Apply only to bar traces

# Format x-axis labels to quarters
fig.update_xaxes(
    tickmode='array',
    tickvals=EMPLOYMENTCOST.index,
    ticktext=EMPLOYMENTCOST.index.to_series().dt.to_period("Q").astype(str)
)

# Display the plot
fig.show()

### Households/Nonprofit Exposure to Equities

In [ ]:
HOUSEHOLDS = web.DataReader('BOGZ1FL153064476Q', 'fred', start)

In [ ]:
HOUSEHOLDS

            BOGZ1FL153064476Q
DATE
2020-01-01          20.818672
2020-04-01          23.917530
2020-07-01          25.162663
2020-10-01          27.593319
2021-01-01          28.485714
2021-04-01          29.301930
2021-07-01          28.676827
2021-10-01          29.131182
2022-01-01          27.550334
2022-04-01          23.721236
2022-07-01          23.080647
2022-10-01          24.244132
2023-01-01          25.284923
2023-04-01          25.939181
2023-07-01          25.144637
2023-10-01          26.834116
2024-01-01          28.070433
2024-04-01          28.076240
2024-07-01          29.355902

In [ ]:
px.line(HOUSEHOLDS, x=HOUSEHOLDS.index, y='BOGZ1FL153064476Q')

### Households/Nonprofit Exposure to Equities e Average Fed Funds Rate

In [ ]:
import pandas_datareader.data as web
import datetime
import plotly.graph_objects as go

start = datetime.datetime(2014, 1, 1)
HOUSEHOLDS = web.DataReader('BOGZ1FL153064476Q', 'fred', start)
AVERAGEFED = web.DataReader('DFF', 'fred', start)

# Converter as datas para o formato trimestral para os ticks
HOUSEHOLDS['Quarter'] = HOUSEHOLDS.index.to_period('Q')
AVERAGEFED['Quarter'] = AVERAGEFED.index.to_period('Q')

fig = go.Figure()

# Manter as datas originais (datetime) para os valores do eixo x
fig.add_trace(go.Scatter(x=HOUSEHOLDS.index,  # Changed to HOUSEHOLDS.index
                         y=HOUSEHOLDS['BOGZ1FL153064476Q'],
                         mode='lines',
                         name='HOUSEHOLDS',
                         line=dict(color='blue')))

# Manter as datas originais (datetime) para os valores do eixo x
fig.add_trace(go.Scatter(x=AVERAGEFED.index,  # Changed to AVERAGEFED.index
                         y=AVERAGEFED['DFF'],
                         mode='lines',
                         name='AVERAGE FEDFUNDSRATE',
                         line=dict(color='darkorange')))

fig.update_layout(title='HOUSEHOLDS vs AVERAGEFEDFUNDSRATE',
                  xaxis_title='Data',
                  yaxis_title='Valor')

# Ajustar a configuração do eixo x para exibir os trimestres
# Convert Period objects to strings for JSON serialization
fig.update_xaxes(
    tickmode = 'array',
    tickvals = HOUSEHOLDS.index,  # Use original datetime index
    ticktext = HOUSEHOLDS['Quarter'].unique().astype(str)  # Convert to strings
)

fig.show()

### UST10Y - UST02Y

In [ ]:
US10US02 = web.DataReader('T10Y2Y', 'fred', start)

In [ ]:
US10US02

            T10Y2Y
DATE
2000-01-03    0.20
2000-01-04    0.19
2000-01-05    0.24
2000-01-06    0.22
2000-01-07    0.21
...            ...
2025-02-10    0.23
2025-02-11    0.25
2025-02-12    0.26
2025-02-13    0.21
2025-02-14    0.21

[6555 rows x 1 columns]

In [ ]:
px.line(US10US02, x=US10US02.index, y='T10Y2Y')

### UST02Y - UST03MY

In [ ]:
US02US03 = web.DataReader('T10Y3M', 'fred', start)

In [ ]:
US02US03

            T10Y3M
DATE
2000-01-03    1.10
2000-01-04    1.06
2000-01-05    1.18
2000-01-06    1.16
2000-01-07    1.14
...            ...
2025-02-10    0.16
2025-02-11    0.19
2025-02-12    0.27
2025-02-13    0.18
2025-02-14    0.13

[6555 rows x 1 columns]

In [ ]:
px.line(US02US03, x=US02US03.index, y='T10Y3M')

### UST10Y - UST02Y e UST02Y - UST03MY

In [ ]:
import pandas_datareader.data as web
import datetime
import plotly.express as px

start = datetime.datetime(2000, 1, 1)  # Define a data de início

# Obtém os dados do US10US02 e US02US03 do FRED
US10US02 = web.DataReader('T10Y2Y', 'fred', start)
US02US03 = web.DataReader('T10Y3M', 'fred', start)

# Cria o gráfico com Plotly Express
fig = px.line(US10US02, x=US10US02.index, y='T10Y2Y', title='US10US02 and US02US03', color_discrete_sequence=['blue'])
fig.data[0].name = 'US10US02'

fig.add_scatter(x=US02US03.index, y=US02US03['T10Y3M'], mode='lines',
                name='US02US03', line=dict(color='darkorange'))

# Adiciona linha preta no 0
fig.add_shape(type='line',
              x0=US10US02.index.min(),  # Começa no mínimo do eixo x
              y0=0,                   # y = 0
              x1=US10US02.index.max(),  # Termina no máximo do eixo x
              y1=0,                   # y = 0
              line=dict(color='black'))

# Exibe o gráfico
fig.show()

### UST10Y - UST02Y e Initial Claims(Average)

In [ ]:
import pandas_datareader.data as web
import datetime
import plotly.express as px
from scipy.stats import zscore

start = datetime.datetime(2000, 1, 1)
US10US02 = web.DataReader('T10Y2Y', 'fred', start)
PedidosIniciais = web.DataReader('ICSA', 'fred', start)

# Apply zscore only to PedidosIniciais
PedidosIniciais['ICSA_zscore'] = zscore(PedidosIniciais['ICSA'])

# Plot US10US02 with normal values and PedidosIniciais with zscore
fig = px.area(US10US02, x=US10US02.index, y='T10Y2Y',
             title='US10US02 e INITIAL CLAIMS (AVERAGE)',
             color_discrete_sequence=['#FF8C00'])

fig.add_scatter(x=PedidosIniciais.index, y=PedidosIniciais['ICSA_zscore'], mode='lines',
                name='INITIAL CLAIMS(AVERAGE)', line=dict(color='blue'))

fig.show()

### Average Fed Funds Rate

In [ ]:
AVERAGEFED = web.DataReader('DFF', 'fred', start)

In [ ]:
AVERAGEFED

             DFF
DATE
2020-01-01  1.55
2020-01-02  1.55
2020-01-03  1.55
2020-01-04  1.55
2020-01-05  1.55
...          ...
2025-02-09  4.33
2025-02-10  4.33
2025-02-11  4.33
2025-02-12  4.33
2025-02-13  4.33

[1871 rows x 1 columns]

In [ ]:
px.line(AVERAGEFED, x=AVERAGEFED.index, y='DFF')

### Real Money Market Funds (Tri)

In [ ]:
import pandas_datareader.data as web
import datetime
import plotly.express as px

start = datetime.datetime(2000, 1, 1)
REALMONEYMARKETFUNDS = web.DataReader('WRMFNS', 'fred', start)
px.line(REALMONEYMARKETFUNDS, x=REALMONEYMARKETFUNDS.index, y='WRMFNS', title='REAL MONEY MARKET FUNDS (TRI)')  # Plota o gráfico

### Retail Money Market Funds (TRI) E Fed Funds Rate (FFR)

In [ ]:
import pandas_datareader.data as web
import datetime
import plotly.graph_objects as go
from scipy.stats import zscore

start = datetime.datetime(2000, 1, 1)

# Fetch the data
FFR = web.DataReader('DFF', 'fred', start)
REALMONEYMARKETFUNDS = web.DataReader('WRMFNS', 'fred', start)

# Normalize the data using z-scores
FFR['DFF_zscore'] = zscore(FFR['DFF'])
REALMONEYMARKETFUNDS['WRMFNS_zscore'] = zscore(REALMONEYMARKETFUNDS['WRMFNS'])

# Create the figure
fig = go.Figure()

# Add FFR trace (blue)
fig.add_trace(go.Scatter(
    x=FFR.index,
    y=FFR['DFF_zscore'],  # Using normalized data
    mode='lines',
    name='FFR',
    line=dict(color='blue')
))

# Add REALMONEYMARKETFUNDS trace (orange)
fig.add_trace(go.Scatter(
    x=REALMONEYMARKETFUNDS.index,
    y=REALMONEYMARKETFUNDS['WRMFNS_zscore'],  # Using normalized data
    mode='lines',
    name='REALMONEYMARKETFUNDS',
    line=dict(color='darkorange')
))

# Update layout
fig.update_layout(
    title='FFR vs REALMONEYMARKETFUNDS (Normalized)',
    xaxis_title='Data',
    yaxis_title='Z-score'
)

# Show the figure
fig.show()

### Delinquency Rate on Credit Cards

In [ ]:
DELINQUENCY = web.DataReader('DRCCLACBS', 'fred', start)

In [ ]:
DELINQUENCY

            DRCCLACBS
DATE
2020-01-01       2.66
2020-04-01       2.45
2020-07-01       2.00
2020-10-01       2.12
2021-01-01       1.86
2021-04-01       1.59
2021-07-01       1.54
2021-10-01       1.57
2022-01-01       1.67
2022-04-01       1.84
2022-07-01       2.07
2022-10-01       2.26
2023-01-01       2.45
2023-04-01       2.76
2023-07-01       2.97
2023-10-01       3.09
2024-01-01       3.15
2024-04-01       3.24
2024-07-01       3.23

In [ ]:
px.line(DELINQUENCY, x=DELINQUENCY.index, y='DRCCLACBS')

### Household Debt Service to Disposable Income

In [ ]:
HOUSEHOLDDEBT = web.DataReader('TDSP', 'fred', start)

In [ ]:
HOUSEHOLDDEBT

                 TDSP
DATE
2020-01-01  11.587379
2020-04-01   9.739372
2020-07-01  10.067065
2020-10-01  10.404484
2021-01-01   9.084982
2021-04-01   9.889169
2021-07-01  10.057423
2021-10-01  10.281331
2022-01-01  10.512948
2022-04-01  10.719180
2022-07-01  10.598597
2022-10-01  10.780190
2023-01-01  10.635344
2023-04-01  10.675248
2023-07-01  10.866162
2023-10-01  11.230787
2024-01-01  11.160256
2024-04-01  11.159134
2024-07-01  11.298014

In [ ]:
px.line(HOUSEHOLDDEBT, x=HOUSEHOLDDEBT.index, y='TDSP')

### Unit Labor Cost

In [ ]:
UNITLABOR = web.DataReader('PRS85006112', 'fred', start)

In [ ]:
UNITLABOR

            PRS85006112
DATE
2020-01-01         11.9
2020-04-01          3.8
2020-07-01        -11.6
2020-10-01         14.1
2021-01-01         -2.3
2021-04-01          6.3
2021-07-01          8.0
2021-10-01          2.9
2022-01-01          6.9
2022-04-01          3.7
2022-07-01          7.4
2022-10-01         -2.4
2023-01-01          3.5
2023-04-01          2.6
2023-07-01          1.2
2023-10-01          0.9
2024-01-01          8.5
2024-04-01         -1.1
2024-07-01          0.5
2024-10-01          3.0

In [ ]:
px.line(UNITLABOR, x=UNITLABOR.index, y='PRS85006112')

###M1 E M2

M1

In [ ]:
M1 = web.DataReader('WM1NS', 'fred', start)

In [ ]:
M1

              WM1NS
DATE
2000-01-03   1199.4
2000-01-10   1134.2
2000-01-17   1122.9
2000-01-24   1111.7
2000-01-31   1108.7
...             ...
2024-12-09  18504.0
2024-12-16  18549.7
2024-12-23  18584.6
2024-12-30  18587.3
2025-01-06  18580.1

[1306 rows x 1 columns]

In [ ]:
px.line(M1, x=M1.index, y='WM1NS')

M2

In [ ]:
M2 = web.DataReader('M2SL', 'fred', start)

In [ ]:
M2

               M2SL
DATE
2000-01-01   4667.6
2000-02-01   4680.9
2000-03-01   4711.7
2000-04-01   4767.8
2000-05-01   4755.7
...             ...
2024-08-01  21141.3
2024-09-01  21222.8
2024-10-01  21312.5
2024-11-01  21448.3
2024-12-01  21533.8

[300 rows x 1 columns]

In [ ]:
px.line(M2, x=M2.index, y='M2SL')

M1 (TRI) E M2 (TRI)

In [ ]:
import pandas_datareader.data as web
import datetime
import plotly.graph_objects as go

start = datetime.datetime(2000, 1, 1)
M1 = web.DataReader('WM1NS', 'fred', start)
M2 = web.DataReader('M2SL', 'fred', start)

fig = go.Figure()

fig.add_trace(go.Scatter(x=M1.index, y=M1['WM1NS'],
                         mode='lines',
                         name='M1',
                         line=dict(color='blue')))

fig.add_trace(go.Scatter(x=M2.index, y=M2['M2SL'],
                         mode='lines',
                         name='M2',
                         line=dict(color='darkorange')))

fig.update_layout(title='M1 e M2',
                  xaxis_title='Data',
                  yaxis_title='Valor')

fig.show()

### Reverse Repo

In [ ]:
ReverseRepo = web.DataReader('RRPONTSYD', 'fred', start)

In [ ]:
ReverseRepo

            RRPONTSYD
DATE
2003-02-07      2.500
2003-02-10        NaN
2003-02-11        NaN
2003-02-12        NaN
2003-02-13        NaN
...               ...
2025-02-12     67.670
2025-02-13     67.820
2025-02-14     58.770
2025-02-17        NaN
2025-02-18     77.817

[5748 rows x 1 columns]

In [ ]:
# Defina a data de início
start_date = '2013-01-01'

# Filtre o DataFrame para incluir apenas dados a partir da data de início
filtered_data = ReverseRepo[ReverseRepo.index >= pd.to_datetime(start_date)]

# Crie o gráfico de área
fig = px.area(filtered_data, x=filtered_data.index, y='RRPONTSYD')
fig.update_traces(line_color='blue', fillcolor='rgba(0, 0, 255, 0.5)')
fig.show()

# <span style="color: gray;">**US** **BUDGET** (**ANNUAL** **DATA**)</span>

### Gonvernment Deficit as % to GDP

In [ ]:
DEFICITGOV = web.DataReader('FYFSGDA188S', 'fred', start)

In [ ]:
DEFICITGOV

            FYFSGDA188S
DATE
2020-01-01    -14.66910
2021-01-01    -11.71965
2022-01-01     -5.29060
2023-01-01     -6.11543
2024-01-01     -6.28127

In [ ]:
px.line(DEFICITGOV, x=DEFICITGOV.index, y='FYFSGDA188S')

### Unemployment Rate

In [ ]:
Unemploy = web.DataReader('Unrate', 'fred', start)

In [ ]:
Unemploy

            Unrate
DATE
2020-01-01     3.6
2020-02-01     3.5
2020-03-01     4.4
2020-04-01    14.8
2020-05-01    13.2
...            ...
2024-09-01     4.1
2024-10-01     4.1
2024-11-01     4.2
2024-12-01     4.1
2025-01-01     4.0

[61 rows x 1 columns]

In [ ]:
px.line(Unemploy, x=Unemploy.index, y='Unrate')

# <span style="color: gray;">**ÍNDICES** **AMERICANOS**</span>

### SP500

In [ ]:
import pandas_datareader.data as web
import datetime
import plotly.express as px

start = datetime.datetime(2012, 1, 1)
INDICESP500 = web.DataReader('SP500', 'fred', start)
px.line(INDICESP500, x=INDICESP500.index, y='SP500', title='SP500')  # Plota o gráfico

### Nasdaq

In [ ]:
import pandas_datareader.data as web
import datetime
import plotly.express as px

start = datetime.datetime(2012, 1, 1)
INDICENASDAQ = web.DataReader('NASDAQCOM', 'fred', start)
px.line(INDICENASDAQ, x=INDICENASDAQ.index, y='NASDAQCOM', title='NASDAQ')  # Plota o gráfico

### Russel 2000

In [ ]:
import pandas_datareader.data as web
import datetime
import plotly.express as px

start = datetime.datetime(2012, 1, 1)
INDICERUSSELL = web.DataReader('RVXCLS', 'fred', start)
px.line(INDICERUSSELL, x=INDICERUSSELL.index, y='RVXCLS', title='RUSSELL')  # Plota o gráfico

### AVERAGE INDICES US

In [ ]:
import pandas_datareader.data as web
import datetime
import plotly.graph_objects as go

start = datetime.datetime(2020, 1, 1)  # Define a data de início

# Coletar os dados dos ativos
INDICESP500 = web.DataReader('SP500', 'fred', start)
INDICENASDAQ = web.DataReader('NASDAQCOM', 'fred', start)
INDICERUSSELL = web.DataReader('RVXCLS', 'fred', start)

# Criar o gráfico com Plotly Graph Objects
fig = go.Figure()

# Adicionar traço de linha para INDICESP500 (azul claro)
fig.add_trace(go.Scatter(x=INDICESP500.index, y=INDICESP500['SP500'],
                         mode='lines', name='INDICESP500',
                         line=dict(color='lightskyblue')))

# Adicionar traço de linha para INDICENASDAQ (verde claro)
fig.add_trace(go.Scatter(x=INDICENASDAQ.index, y=INDICENASDAQ['NASDAQCOM'],
                         mode='lines', name='INDICENASDAQ',
                         line=dict(color='lightgreen')))

# Adicionar traço de linha para INDICERUSSELL (azul escuro)
fig.add_trace(go.Scatter(x=INDICERUSSELL.index, y=INDICERUSSELL['RVXCLS'],
                         mode='lines', name='INDICERUSSELL',
                         line=dict(color='darkblue')))

# Personalizar o layout do gráfico
fig.update_layout(title='Comparação de Índices',
                  xaxis_title='Data',
                  yaxis_title='Valor')

# Exibir o gráfico
fig.show()

# <span style="color: gray;">**TREASURY BONDS**

### 3 Meses

In [ ]:
t3mo = web.DataReader('DGS3MO', 'fred', start)

In [ ]:
t3mo

            DGS3MO
DATE
2000-01-03    5.48
2000-01-04    5.43
2000-01-05    5.44
2000-01-06    5.41
2000-01-07    5.38
...            ...
2025-02-05    4.33
2025-02-06    4.34
2025-02-07    4.35
2025-02-10    4.35
2025-02-11    4.35

[6552 rows x 1 columns]

In [ ]:
px.line(data_frame=t3mo, x=t3mo.index, y='DGS3MO')

### 10 Anos

In [ ]:
t10 = web.DataReader('DGS10', 'fred', start)

In [ ]:
t10

            DGS10
DATE
2000-01-03   6.58
2000-01-04   6.49
2000-01-05   6.62
2000-01-06   6.57
2000-01-07   6.52
...           ...
2025-02-05   4.43
2025-02-06   4.45
2025-02-07   4.49
2025-02-10   4.51
2025-02-11   4.54

[6552 rows x 1 columns]

In [ ]:
px.line(data_frame=t10, x=t10.index, y='DGS10')

### US3M & US10Y

In [ ]:
import plotly.express as px
import pandas as pd
import pandas_datareader.data as web
import datetime

start = datetime.datetime(2022, 1, 1)

# Fetch data (if not already done)
t3mo = web.DataReader('DGS3MO', 'fred', start)
t10 = web.DataReader('DGS10', 'fred', start)

# Merge and rename columns
merged_df = pd.merge(t3mo, t10, left_index=True, right_index=True)
merged_df = merged_df.rename(columns={"DGS3MO": "3 Meses", "DGS10": "10 Anos"})

# Create the plot
fig = px.line(merged_df, x=merged_df.index, y=['3 Meses', '10 Anos'])

# Format x-axis labels to show year and month
fig.update_xaxes(
    tickformat="%Y-%m",  # Format string for year and month
    dtick="M1",          # Show ticks for each month
    title_text="Data"  # Set x-axis title (optional)
)

fig.show()

# <span style="color: gray;">**EMPREGO**</span>

### Taxa de Desemprego

In [ ]:
desemprego = web.DataReader('UNRATE', 'fred', start)

In [ ]:
desemprego

            UNRATE
DATE
2000-01-01     4.0
2000-02-01     4.1
2000-03-01     4.0
2000-04-01     3.8
2000-05-01     4.0
...            ...
2024-09-01     4.1
2024-10-01     4.1
2024-11-01     4.2
2024-12-01     4.1
2025-01-01     4.0

[301 rows x 1 columns]

In [ ]:
px.line(data_frame=desemprego, x=desemprego.index, y='UNRATE')

In [ ]:
var_desemprego = desemprego.pct_change()[1:]

In [ ]:
px.bar(data_frame=var_desemprego, x=var_desemprego.index, y='UNRATE')

In [ ]:
px.bar(y=zscore(var_desemprego), x=var_desemprego.index, labels={'y':'desvios-padrão'})

ValueError: All arguments should have the same length. The length of argument `wide_variable_0` is 1, whereas the length of previously-processed arguments ['x'] is 300

### Pessoas Empregadas

In [ ]:
empregos = web.DataReader('PAYEMS', 'fred', start)

In [ ]:
empregos

            PAYEMS
DATE
2000-01-01  131011
2000-02-01  131121
2000-03-01  131604
2000-04-01  131883
2000-05-01  132105
...            ...
2024-09-01  158314
2024-10-01  158358
2024-11-01  158619
2024-12-01  158926
2025-01-01  159069

[301 rows x 1 columns]

In [ ]:
px.line(data_frame=empregos, x=empregos.index, y='PAYEMS')

In [ ]:
px.bar(data_frame=empregos.pct_change(), x=empregos.index, y='PAYEMS')

# <span style="color: gray;">**IMPRESSORA** **DE** **DÓLAR**</span>

### Impressora de Dólar - Agregado M2 (Papel moeda, depósitos à vista e à prazo)

In [ ]:
m2 = web.DataReader('M2', 'fred', start)

In [ ]:
m2

                 M2
DATE
2000-01-03   4653.1
2000-01-10   4657.6
2000-01-17   4659.8
2000-01-24   4667.0
2000-01-31   4667.7
...             ...
2020-04-27  17566.6
2020-05-04  17765.3
2020-05-11  17990.4
2020-05-18  18083.5
2020-05-25  18115.1

[1065 rows x 1 columns]

In [ ]:
px.line(data_frame=m2, x=m2.index, y='M2')

# <span style="color: gray;">**ATIVOS** **DO** **FED**</span>

### Ativos do FED

In [ ]:
ativos = web.DataReader('WALCL', 'fred', start)

In [ ]:
ativos

              WALCL
DATE
2020-01-01  4173626
2020-01-08  4149544
2020-01-15  4175850
2020-01-22  4145912
2020-01-29  4151630
...             ...
2025-01-08  6853554
2025-01-15  6834070
2025-01-22  6831760
2025-01-29  6818186
2025-02-05  6810935

[267 rows x 1 columns]

In [ ]:
px.line(data_frame=ativos, x=ativos.index, y='WALCL')